-- =================================================================
-- SETUP VALIDATION QUERIES
-- =================================================================
-- This file contains all validation queries used to verify that
-- the Snowflake database setup completed successfully.
-- Each query validates a specific aspect of the setup.
-- =================================================================

-- Database and Schema Validation
-- Verify core database and schema structure exists
SHOW DATABASES LIKE 'BETTERJOBS_DB';

SHOW SCHEMAS IN DATABASE BETTERJOBS_DB;

SHOW ROLES LIKE 'BETTERJOBS_ROLE';

-- Table Structure Validation
-- Verify all expected tables exist in each schema
SHOW TABLES IN SCHEMA BETTERJOBS_DB.RAW;

SHOW TABLES IN SCHEMA BETTERJOBS_DB.STAGE;

SHOW TABLES IN SCHEMA BETTERJOBS_DB.ANALYTICS;

-- Data Population Validation
-- Verify that static lookup tables have been populated with data
SELECT COUNT(*) as COUNTRIES_MAPPING_COUNT FROM BETTERJOBS_DB.STAGE.COUNTRIES_MAPPING;

SELECT COUNT(*) as KEYWORD_STANDARDIZATION_RULES_COUNT FROM BETTERJOBS_DB.STAGE.KEYWORD_STANDARDIZATION_RULES;

SELECT COUNT(*) as KEYWORD_TYPE_MAPPING_COUNT FROM BETTERJOBS_DB.STAGE.KEYWORD_TYPE_MAPPING;

SELECT COUNT(*) as LOCATION_METRO_AREA_MAPPING_COUNT FROM BETTERJOBS_DB.STAGE.LOCATION_METRO_AREA_MAPPING;

SELECT COUNT(*) as LOCATION_REGION_MAPPING_COUNT FROM BETTERJOBS_DB.STAGE.LOCATION_REGION_MAPPING;

SELECT COUNT(*) as LOCATION_TECH_HUB_MAPPING_COUNT FROM BETTERJOBS_DB.STAGE.LOCATION_TECH_HUB_MAPPING;

SELECT COUNT(*) as LOCATION_STANDARDIZATION_RULES_COUNT FROM BETTERJOBS_DB.STAGE.LOCATION_STANDARDIZATION_RULES;

SELECT COUNT(*) as US_STATES_MAPPING_COUNT FROM BETTERJOBS_DB.STAGE.US_STATES_MAPPING;
