-- Creating a small warehouse for the project
CREATE WAREHOUSE IF NOT EXISTS BETTERJOBS_WH
    WITH WAREHOUSE_SIZE = 'Small'
    AUTO_SUSPEND = 60
    AUTO_RESUME = true;

-- Creating the DB
CREATE DATABASE IF NOT EXISTS BETTERJOBS_DB;

/* STEPS BELOW ARE ONLY NEEDED IF YOU ARE USING A DEDICATED USER FOR THE PROJECT */

-- Creating role specific to the project
CREATE ROLE IF NOT EXISTS BETTERJOBS_ROLE;

-- Granting necessary permission to the role
GRANT USAGE ON WAREHOUSE BETTERJOBS_WH TO ROLE BETTERJOBS_ROLE;
GRANT USAGE ON DATABASE BETTERJOBS_DB TO ROLE BETTERJOBS_ROLE;
GRANT CREATE SCHEMA ON DATABASE BETTERJOBS_DB TO ROLE BETTERJOBS_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE BETTERJOBS_DB TO ROLE BETTERJOBS_ROLE;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE BETTERJOBS_DB TO ROLE BETTERJOBS_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE BETTERJOBS_DB TO ROLE BETTERJOBS_ROLE;

-- Granting the BETTERJOBS_ROLE to the user
GRANT ROLE BETTERJOBS_ROLE TO USER your_username_here

-- Setting default role and warehouse for user
ALTER USER your_username_here SET DEFAULT_ROLE = BETTERJOBS_ROLE;
ALTER USER your_username_here SET DEFAULT_WAREHOUSE = BETTERJOBS_WH;