/*********** TABLES ***********/

-- COMPANY_PROFILES
create or replace TABLE BETTERJOBS_DB.STAGE.COMPANY_PROFILES (
	COMPANY_ID VARCHAR(16777216) NOT NULL,
	COMPANY_NAME_STANDARDIZED VARCHAR(16777216),
	COMPANY_INDUSTRY_STANDARDIZED VARCHAR(16777216),
	COMPANY_SIZE_CATEGORY VARCHAR(16777216),
	EMPLOYEE_COUNT_RANGE VARCHAR(16777216),
	FUNDING_STAGE VARCHAR(16777216),
	HEADQUARTERS_LOCATION VARCHAR(16777216),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (COMPANY_ID)
);

-- JOBS_LLM_ENRICHED
create or replace TABLE BETTERJOBS_DB.STAGE.JOBS_LLM_ENRICHED cluster by (llm_processing_timestamp)(
	JOB_UID VARCHAR(16777216) NOT NULL,
	SALARY_MIN NUMBER(38,0),
	SALARY_MAX NUMBER(38,0),
	SALARY_CURRENCY VARCHAR(16777216) DEFAULT 'USD',
	SALARY_PERIOD VARCHAR(16777216),
	SALARY_TYPE VARCHAR(16777216),
	EQUITY_MENTIONED BOOLEAN DEFAULT FALSE,
	BONUS_MENTIONED BOOLEAN DEFAULT FALSE,
	SALARY_CONFIDENCE FLOAT,
	MIN_YEARS_EXPERIENCE NUMBER(38,0),
	MAX_YEARS_EXPERIENCE NUMBER(38,0),
	EXPERIENCE_LEVEL VARCHAR(16777216),
	SPECIFIC_TECHNOLOGIES_YEARS VARIANT,
	EDUCATION_REQUIREMENTS VARIANT,
	CERTIFICATIONS VARIANT,
	EXPERIENCE_CONFIDENCE FLOAT,
	TECHNICAL_SKILLS VARIANT,
	SOFT_SKILLS VARIANT,
	SKILLS_CONFIDENCE FLOAT,
	WORK_TYPE VARCHAR(16777216),
	REMOTE_FLEXIBILITY VARCHAR(16777216),
	TRAVEL_REQUIREMENTS VARCHAR(16777216),
	OFFICE_LOCATIONS VARIANT,
	TIMEZONE_REQUIREMENTS VARCHAR(16777216),
	WORK_ARRANGEMENT_CONFIDENCE FLOAT,
	JOB_FAMILY VARCHAR(16777216),
	JOB_SUB_FAMILY VARCHAR(16777216),
	SENIORITY_LEVEL VARCHAR(16777216),
	PRIMARY_KEYWORDS VARIANT,
	INDUSTRY_KEYWORDS VARIANT,
	ROLE_TYPE VARCHAR(16777216),
	TEAM_SIZE VARCHAR(16777216),
	CLASSIFICATION_CONFIDENCE FLOAT,
	LLM_PROCESSED BOOLEAN DEFAULT TRUE,
	LLM_PROCESSING_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	LLM_MODEL_VERSION VARCHAR(16777216) DEFAULT 'gemini-2.5-flash-preview-04-17',
	LLM_OVERALL_CONFIDENCE FLOAT,
	LLM_NEEDS_MANUAL_REVIEW BOOLEAN DEFAULT FALSE,
	EXTRACTION_CONFIDENCE_AVG FLOAT,
	KEYWORD_QUALITY_SCORE FLOAT,
	VALIDATION_STATUS VARCHAR(16777216) DEFAULT 'pending',
	LAST_UPDATED TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (JOB_UID),
	constraint FK_JOBS_LLM_JOB_UID foreign key (JOB_UID) references BETTERJOBS_DB.STAGE.JOBS_UNIFIED(JOB_UID)
);

-- JOBS_UNIFIED
create or replace TABLE BETTERJOBS_DB.STAGE.JOBS_UNIFIED (
	JOB_UID VARCHAR(16777216) NOT NULL,
	JOB_ID VARCHAR(16777216),
	COMPANY_ID VARCHAR(16777216),
	PLATFORM VARCHAR(16777216),
	JOB_TITLE_CLEAN VARCHAR(16777216),
	JOB_DESCRIPTION_CLEAN VARCHAR(16777216),
	COMPANY_NAME_CLEAN VARCHAR(16777216),
	LOCATION_STANDARDIZED VARCHAR(16777216),
	JOB_URL VARCHAR(16777216),
	DATE_POSTED DATE,
	DATE_RETRIEVED TIMESTAMP_NTZ(9),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	EMPLOYMENT_STATUS VARCHAR(16777216),
	DEPARTMENT VARCHAR(16777216),
	DETECTED_LANGUAGE VARCHAR(16777216),
	LANGUAGE_CONFIDENCE FLOAT,
	IS_ENGLISH BOOLEAN,
	LANGUAGE_DETECTION_METHOD VARCHAR(16777216),
	PLATFORM_SPECIFIC_DATA VARIANT,
	TRANSFORMATION_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	DATA_QUALITY_SCORE FLOAT,
	SOURCE_RAW_TABLE VARCHAR(16777216),
	RAW_DATA VARIANT,
	PARTITION_DATE DATE,
	primary key (JOB_UID)
);

-- JOB_KEYWORDS_BRIDGE
create or replace TABLE BETTERJOBS_DB.STAGE.JOB_KEYWORDS_BRIDGE cluster by (JOB_UID, KEYWORD_SOURCE)(
	BRIDGE_ID VARCHAR(16777216) NOT NULL,
	JOB_UID VARCHAR(16777216) NOT NULL,
	KEYWORD_ID VARCHAR(16777216) NOT NULL,
	KEYWORD_SOURCE VARCHAR(16777216) NOT NULL,
	ORIGINAL_TEXT VARCHAR(16777216),
	EXTRACTION_CONFIDENCE FLOAT,
	STANDARDIZATION_CONFIDENCE FLOAT,
	OVERALL_CONFIDENCE FLOAT,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (BRIDGE_ID),
	constraint FK_JOB_KEYWORDS_JOB_UID foreign key (JOB_UID) references BETTERJOBS_DB.STAGE.JOBS_UNIFIED(JOB_UID),
	constraint FK_JOB_KEYWORDS_KEYWORD_ID foreign key (KEYWORD_ID) references BETTERJOBS_DB.STAGE.KEYWORDS_NORMALIZED(KEYWORD_ID)
);

-- JOB_LOCATIONS_BRIDGE
create or replace TABLE BETTERJOBS_DB.STAGE.JOB_LOCATIONS_BRIDGE cluster by (JOB_UID, LOCATION_SOURCE)(
	BRIDGE_ID VARCHAR(16777216) NOT NULL,
	JOB_UID VARCHAR(16777216) NOT NULL,
	LOCATION_ID VARCHAR(16777216) NOT NULL,
	LOCATION_SOURCE VARCHAR(16777216) NOT NULL,
	ORIGINAL_TEXT VARCHAR(16777216),
	LOCATION_CONTEXT VARCHAR(16777216),
	WORK_ARRANGEMENT VARCHAR(16777216),
	EXTRACTION_CONFIDENCE FLOAT,
	STANDARDIZATION_CONFIDENCE FLOAT,
	OVERALL_CONFIDENCE FLOAT,
	PROCESSING_METHOD VARCHAR(16777216) DEFAULT 'llm_auto',
	NEEDS_REVIEW BOOLEAN DEFAULT FALSE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(16777216) DEFAULT 'system',
	primary key (BRIDGE_ID),
	constraint FK_JOB_LOCATIONS_JOB_UID foreign key (JOB_UID) references BETTERJOBS_DB.STAGE.JOBS_UNIFIED(JOB_UID),
	constraint FK_JOB_LOCATIONS_LOCATION_ID foreign key (LOCATION_ID) references BETTERJOBS_DB.STAGE.LOCATIONS_NORMALIZED(LOCATION_ID)
);

-- JOB_SKILLS_BRIDGE
create or replace TABLE BETTERJOBS_DB.STAGE.JOB_SKILLS_BRIDGE cluster by (JOB_UID, SKILL_CATEGORY)(
	BRIDGE_ID VARCHAR(16777216) NOT NULL,
	JOB_UID VARCHAR(16777216) NOT NULL,
	SKILL_ID VARCHAR(16777216) NOT NULL,
	SKILL_SOURCE VARCHAR(16777216) NOT NULL,
	SKILL_CATEGORY VARCHAR(16777216) NOT NULL,
	ORIGINAL_TEXT VARCHAR(16777216),
	EXTRACTION_CONFIDENCE FLOAT,
	STANDARDIZATION_CONFIDENCE FLOAT,
	OVERALL_CONFIDENCE FLOAT,
	SKILL_CONTEXT VARCHAR(16777216),
	EXPERIENCE_LEVEL_CONTEXT VARCHAR(16777216),
	PROCESSING_METHOD VARCHAR(16777216) DEFAULT 'llm_auto',
	NEEDS_REVIEW BOOLEAN DEFAULT FALSE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(16777216) DEFAULT 'system',
	primary key (BRIDGE_ID),
	constraint FK_JOB_SKILLS_JOB_UID foreign key (JOB_UID) references BETTERJOBS_DB.STAGE.JOBS_UNIFIED(JOB_UID),
	constraint FK_JOB_SKILLS_SKILL_ID foreign key (SKILL_ID) references BETTERJOBS_DB.STAGE.SKILLS_NORMALIZED(SKILL_ID)
);

-- KEYWORDS_NORMALIZED
create or replace TABLE BETTERJOBS_DB.STAGE.KEYWORDS_NORMALIZED cluster by (KEYWORD_TYPE, KEYWORD_TEXT)(
	KEYWORD_ID VARCHAR(16777216) NOT NULL,
	KEYWORD_TEXT VARCHAR(16777216) NOT NULL,
	KEYWORD_TEXT_CLEAN VARCHAR(16777216) NOT NULL,
	KEYWORD_TYPE VARCHAR(16777216) NOT NULL,
	KEYWORD_CATEGORY VARCHAR(16777216),
	ORIGINAL_VARIANTS VARIANT,
	CANONICAL_FORM VARCHAR(16777216),
	FREQUENCY_COUNT NUMBER(38,0) DEFAULT 0,
	TREND_SCORE FLOAT DEFAULT 0,
	CONFIDENCE_SCORE FLOAT DEFAULT 1,
	APPROVED_BY_ADMIN BOOLEAN DEFAULT FALSE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (KEYWORD_ID)
);

-- KEYWORD_STANDARDIZATION_RULES
create or replace TABLE BETTERJOBS_DB.STAGE.KEYWORD_STANDARDIZATION_RULES cluster by (KEYWORD_TYPE, IS_ACTIVE)(
	RULE_ID VARCHAR(16777216) NOT NULL,
	PATTERN VARCHAR(16777216) NOT NULL,
	STANDARDIZED_TEXT VARCHAR(16777216) NOT NULL,
	KEYWORD_TYPE VARCHAR(16777216) NOT NULL,
	KEYWORD_CATEGORY VARCHAR(16777216),
	CONFIDENCE_SCORE FLOAT DEFAULT 1,
	RULE_TYPE VARCHAR(16777216) DEFAULT 'exact_match',
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (RULE_ID)
);

-- KEYWORD_TYPE_MAPPING
create or replace TABLE BETTERJOBS_DB.STAGE.KEYWORD_TYPE_MAPPING cluster by (KEYWORD_TYPE, IS_ACTIVE)(
	MAPPING_ID VARCHAR(16777216) NOT NULL,
	KEYWORD_TEXT VARCHAR(16777216) NOT NULL,
	KEYWORD_TYPE VARCHAR(16777216) NOT NULL,
	KEYWORD_CATEGORY VARCHAR(16777216) NOT NULL,
	CATEGORY_DESCRIPTION VARCHAR(16777216),
	CONFIDENCE_SCORE FLOAT DEFAULT 1,
	BUSINESS_RELEVANCE VARCHAR(16777216) DEFAULT 'medium',
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (MAPPING_ID)
);

-- LOCATIONS_NORMALIZED
create or replace TABLE BETTERJOBS_DB.STAGE.LOCATIONS_NORMALIZED cluster by (COUNTRY, STATE_PROVINCE, CITY)(
	LOCATION_ID VARCHAR(16777216) NOT NULL,
	LOCATION_NAME VARCHAR(16777216) NOT NULL,
	LOCATION_NAME_CLEAN VARCHAR(16777216) NOT NULL,
	LOCATION_NAME_ORIGINAL VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE_PROVINCE VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	METRO_AREA VARCHAR(16777216),
	REGION VARCHAR(16777216),
	LOCATION_TYPE VARCHAR(16777216),
	IS_REMOTE_FRIENDLY BOOLEAN DEFAULT FALSE,
	IS_MAJOR_TECH_HUB BOOLEAN DEFAULT FALSE,
	COST_OF_LIVING_INDEX FLOAT,
	AVERAGE_SALARY_ADJUSTMENT FLOAT,
	ORIGINAL_VARIANTS VARIANT,
	CONFIDENCE_SCORE FLOAT DEFAULT 1,
	FREQUENCY_COUNT NUMBER(38,0) DEFAULT 0,
	FIRST_SEEN_DATE DATE,
	LAST_SEEN_DATE DATE,
	MANUAL_REVIEW_FLAG BOOLEAN DEFAULT FALSE,
	APPROVED_BY_ADMIN BOOLEAN DEFAULT FALSE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(16777216) DEFAULT 'system',
	primary key (LOCATION_ID)
);

-- LOCATION_MAPPING
create or replace TABLE BETTERJOBS_DB.STAGE.LOCATION_MAPPING (
	LOCATION_RAW VARCHAR(16777216),
	LOCATION_STANDARDIZED VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	METRO_AREA VARCHAR(16777216),
	COST_OF_LIVING_INDEX FLOAT,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- LOCATION_STANDARDIZATION_RULES
create or replace TABLE BETTERJOBS_DB.STAGE.LOCATION_STANDARDIZATION_RULES (
	RULE_ID VARCHAR(16777216) NOT NULL,
	PATTERN VARCHAR(16777216),
	STANDARDIZED_NAME VARCHAR(16777216),
	CITY VARCHAR(16777216),
	STATE_PROVINCE VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	LOCATION_TYPE VARCHAR(16777216),
	CONFIDENCE_SCORE FLOAT DEFAULT 1,
	RULE_TYPE VARCHAR(16777216) DEFAULT 'exact_match',
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (RULE_ID)
);

-- LOCATION_METRO_AREA_MAPPING
create or replace TABLE BETTERJOBS_DB.STAGE.LOCATION_METRO_AREA_MAPPING cluster by (COUNTRY, STATE_PROVINCE)(
	MAPPING_ID VARCHAR(16777216) NOT NULL,
	CITY VARCHAR(16777216) NOT NULL,
	STATE_PROVINCE VARCHAR(16777216) NOT NULL,
	COUNTRY VARCHAR(16777216) NOT NULL,
	METRO_AREA VARCHAR(16777216) NOT NULL,
	IS_PRIMARY_CITY BOOLEAN DEFAULT FALSE,
	CONFIDENCE_SCORE FLOAT DEFAULT 1,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (MAPPING_ID)
);

-- LOCATION_REGION_MAPPING
create or replace TABLE BETTERJOBS_DB.STAGE.LOCATION_REGION_MAPPING cluster by (COUNTRY, REGION)(
	MAPPING_ID VARCHAR(16777216) NOT NULL,
	STATE_PROVINCE VARCHAR(16777216) NOT NULL,
	COUNTRY VARCHAR(16777216) NOT NULL,
	REGION VARCHAR(16777216) NOT NULL,
	REGION_DESCRIPTION VARCHAR(16777216),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (MAPPING_ID)
);

-- LOCATION_TECH_HUB_MAPPING
create or replace TABLE BETTERJOBS_DB.STAGE.LOCATION_TECH_HUB_MAPPING cluster by (COUNTRY, STATE_PROVINCE)(
	MAPPING_ID VARCHAR(16777216) NOT NULL,
	CITY VARCHAR(16777216) NOT NULL,
	STATE_PROVINCE VARCHAR(16777216) NOT NULL,
	COUNTRY VARCHAR(16777216) NOT NULL,
	IS_MAJOR_TECH_HUB BOOLEAN DEFAULT TRUE,
	TECH_HUB_TYPE VARCHAR(16777216),
	HUB_DESCRIPTION VARCHAR(16777216),
	CONFIDENCE_SCORE FLOAT DEFAULT 1,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (MAPPING_ID)
);

-- US_STATES_MAPPING
create or replace TABLE BETTERJOBS_DB.STAGE.US_STATES_MAPPING (
    STATE_ID STRING PRIMARY KEY,
    STATE_NAME_FULL STRING NOT NULL,
    STATE_ABBREVIATION STRING NOT NULL,
    COUNTRY STRING DEFAULT 'United States',
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
) CLUSTER BY (STATE_ABBREVIATION, STATE_NAME_FULL);

-- COUNTRIES_MAPPING
create or replace TABLE BETTERJOBS_DB.STAGE.COUNTRIES_MAPPING (
    COUNTRY_ID STRING PRIMARY KEY,
    COUNTRY_NAME_OFFICIAL STRING NOT NULL,
    COUNTRY_NAME_COMMON STRING NOT NULL,
    COUNTRY_CODE_ISO2 STRING,                       -- ISO 3166-1 alpha-2 (US, CA, GB)
    COUNTRY_CODE_ISO3 STRING,                       -- ISO 3166-1 alpha-3 (USA, CAN, GBR)
    REGION STRING,                                  -- Geographic region
    IS_MAJOR_TECH_HUB BOOLEAN DEFAULT FALSE,       -- Major technology centers
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
) CLUSTER BY (COUNTRY_NAME_COMMON, COUNTRY_CODE_ISO2);


-- SKILLS_NORMALIZED
create or replace TABLE BETTERJOBS_DB.STAGE.SKILLS_NORMALIZED cluster by (SKILL_CATEGORY, SKILL_NAME)(
	SKILL_ID VARCHAR(16777216) NOT NULL,
	SKILL_NAME VARCHAR(16777216) NOT NULL,
	SKILL_NAME_CLEAN VARCHAR(16777216) NOT NULL,
	SKILL_NAME_ORIGINAL VARCHAR(16777216),
	SKILL_CATEGORY VARCHAR(16777216) NOT NULL,
	SKILL_SUBCATEGORY VARCHAR(16777216),
	SKILL_FAMILY VARCHAR(16777216),
	SKILL_TYPE VARCHAR(16777216) DEFAULT 'technical',
	ORIGINAL_VARIANTS VARIANT,
	COMMON_ALIASES VARIANT,
	CANONICAL_FORM VARCHAR(16777216),
	FREQUENCY_COUNT NUMBER(38,0) DEFAULT 0,
	FIRST_SEEN_DATE DATE,
	LAST_SEEN_DATE DATE,
	TREND_DIRECTION VARCHAR(16777216),
	CONFIDENCE_SCORE FLOAT DEFAULT 1,
	MANUAL_REVIEW_FLAG BOOLEAN DEFAULT FALSE,
	APPROVED_BY_ADMIN BOOLEAN DEFAULT FALSE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(16777216) DEFAULT 'system',
	primary key (SKILL_ID)
);

-- SKILLS_TAXONOMY
create or replace TABLE BETTERJOBS_DB.STAGE.SKILLS_TAXONOMY (
	SKILL_NAME VARCHAR(16777216) NOT NULL,
	SKILL_CATEGORY VARCHAR(16777216),
	SKILL_ALIASES VARIANT,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (SKILL_NAME)
);

-- SKILL_CATEGORY_PATTERNS
create or replace TABLE BETTERJOBS_DB.STAGE.SKILL_CATEGORY_PATTERNS cluster by (SKILL_CATEGORY, IS_ACTIVE)(
	PATTERN_ID VARCHAR(16777216) NOT NULL,
	SKILL_CATEGORY VARCHAR(16777216) NOT NULL,
	PATTERN VARCHAR(16777216) NOT NULL,
	PATTERN_TYPE VARCHAR(16777216) DEFAULT 'regex',
	CONFIDENCE_SCORE FLOAT DEFAULT 1,
	DESCRIPTION VARCHAR(16777216),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (PATTERN_ID)
);

-- SKILL_FAMILY_MAPPING
create or replace TABLE BETTERJOBS_DB.STAGE.SKILL_FAMILY_MAPPING cluster by (SKILL_CATEGORY, IS_ACTIVE)(
	MAPPING_ID VARCHAR(16777216) NOT NULL,
	SKILL_CATEGORY VARCHAR(16777216) NOT NULL,
	SKILL_FAMILY VARCHAR(16777216) NOT NULL,
	FAMILY_DESCRIPTION VARCHAR(16777216),
	PRIORITY NUMBER(38,0) DEFAULT 1,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (MAPPING_ID)
);

--SKILL_STANDARDIZATION_RULES
create or replace TABLE BETTERJOBS_DB.STAGE.SKILL_STANDARDIZATION_RULES (
	RULE_ID VARCHAR(16777216) NOT NULL,
	PATTERN VARCHAR(16777216),
	STANDARDIZED_NAME VARCHAR(16777216),
	SKILL_CATEGORY VARCHAR(16777216),
	SKILL_SUBCATEGORY VARCHAR(16777216),
	CONFIDENCE_SCORE FLOAT DEFAULT 1,
	RULE_TYPE VARCHAR(16777216) DEFAULT 'exact_match',
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (RULE_ID)
);

-- TRANSFORMATION_LOGS
create or replace TABLE BETTERJOBS_DB.STAGE.TRANSFORMATION_LOGS (
	LOG_ID VARCHAR(16777216) NOT NULL,
	JOB_ID VARCHAR(16777216),
	TRANSFORMATION_STEP VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	ERROR_MESSAGE VARCHAR(16777216),
	PROCESSING_TIME_SECONDS FLOAT,
	TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (LOG_ID)
);


/*********** VIEWS ***********/

-- DATA_VALIDATION_REPORT
create or replace view BETTERJOBS_DB.STAGE.DATA_VALIDATION_REPORT(
	CHECK_NAME,
	ISSUE_COUNT
) as
WITH VALIDATION_CHECKS AS (
    -- Check 1: Skills without jobs
    SELECT 'orphaned_skills' as CHECK_NAME, COUNT(*) as ISSUE_COUNT
    FROM SKILLS_NORMALIZED sn
    LEFT JOIN JOB_SKILLS_BRIDGE jsb ON sn.SKILL_ID = jsb.SKILL_ID
    WHERE jsb.SKILL_ID IS NULL

    UNION ALL

    -- Check 2: Jobs without skills
    SELECT 'jobs_without_skills' as CHECK_NAME, COUNT(*) as ISSUE_COUNT
    FROM JOBS_UNIFIED ju
    LEFT JOIN JOB_SKILLS_BRIDGE jsb ON ju.JOB_UID = jsb.JOB_UID
    WHERE jsb.JOB_UID IS NULL AND ju.IS_ENGLISH = TRUE

    UNION ALL

    -- Check 3: Low confidence skills
    SELECT 'low_confidence_skills' as CHECK_NAME, COUNT(*) as ISSUE_COUNT
    FROM SKILLS_NORMALIZED
    WHERE CONFIDENCE_SCORE < 0.5

    UNION ALL

    -- Check 4: Duplicate skill names
    SELECT 'duplicate_skill_names' as CHECK_NAME, COUNT(*) - COUNT(DISTINCT SKILL_NAME) as ISSUE_COUNT
    FROM SKILLS_NORMALIZED

    UNION ALL

    -- Check 5: Locations without jobs
    SELECT 'orphaned_locations' as CHECK_NAME, COUNT(*) as ISSUE_COUNT
    FROM LOCATIONS_NORMALIZED ln
    LEFT JOIN JOB_LOCATIONS_BRIDGE jlb ON ln.LOCATION_ID = jlb.LOCATION_ID
    WHERE jlb.LOCATION_ID IS NULL

    UNION ALL

    -- Check 6: Jobs without locations
    SELECT 'jobs_without_locations' as CHECK_NAME, COUNT(*) as ISSUE_COUNT
    FROM JOBS_UNIFIED ju
    LEFT JOIN JOB_LOCATIONS_BRIDGE jlb ON ju.JOB_UID = jlb.JOB_UID
    WHERE jlb.JOB_UID IS NULL AND ju.IS_ENGLISH = TRUE

    UNION ALL

    -- Check 7: Low confidence locations
    SELECT 'low_confidence_locations' as CHECK_NAME, COUNT(*) as ISSUE_COUNT
    FROM LOCATIONS_NORMALIZED
    WHERE CONFIDENCE_SCORE < 0.5
)
SELECT * FROM VALIDATION_CHECKS
WHERE ISSUE_COUNT > 0;

-- JOBS_ENGLISH
-- (Need to review to possibly use tables that are further downstream)
create or replace view BETTERJOBS_DB.STAGE.JOBS_ENGLISH(
	JOB_ID,
	COMPANY_ID,
	PLATFORM,
	JOB_TITLE_CLEAN,
	JOB_DESCRIPTION_CLEAN,
	COMPANY_NAME_CLEAN,
	LOCATION_STANDARDIZED,
	JOB_URL,
	DATE_POSTED,
	DATE_RETRIEVED,
	IS_ACTIVE,
	EMPLOYMENT_STATUS,
	DEPARTMENT,
	DETECTED_LANGUAGE,
	LANGUAGE_CONFIDENCE,
	IS_ENGLISH,
	LANGUAGE_DETECTION_METHOD,
	SALARY_MIN,
	SALARY_MAX,
	SALARY_CURRENCY,
	SALARY_PERIOD,
	SALARY_CONFIDENCE,
	MIN_YEARS_EXPERIENCE,
	MAX_YEARS_EXPERIENCE,
	EXPERIENCE_LEVEL,
	EDUCATION_REQUIREMENTS,
	PROGRAMMING_LANGUAGES,
	DATABASES,
	CLOUD_PLATFORMS,
	FRAMEWORKS,
	TOOLS,
	SOFT_SKILLS,
	WORK_TYPE,
	REMOTE_FLEXIBILITY,
	TRAVEL_REQUIREMENTS,
	OFFICE_LOCATIONS,
	PRIMARY_KEYWORDS,
	INDUSTRY_KEYWORDS,
	ROLE_TYPE_KEYWORDS,
	COMPANY_STAGE_KEYWORDS,
	JOB_FAMILY,
	JOB_SUB_FAMILY,
	PLATFORM_SPECIFIC_DATA,
	TRANSFORMATION_TIMESTAMP,
	DATA_QUALITY_SCORE,
	EXTRACTION_CONFIDENCE_AVG,
	KEYWORD_QUALITY_SCORE,
	SOURCE_RAW_TABLE,
	RAW_DATA,
	PARTITION_DATE
) as
SELECT * FROM jobs_unified
WHERE is_english = TRUE;

-- JOBS_RECENT
-- (Need to review to possibly use tables that are further downstream or even turn into an SP with a parameter for the date range)
create or replace view BETTERJOBS_DB.STAGE.JOBS_RECENT(
	JOB_ID,
	COMPANY_ID,
	PLATFORM,
	JOB_TITLE_CLEAN,
	JOB_DESCRIPTION_CLEAN,
	COMPANY_NAME_CLEAN,
	LOCATION_STANDARDIZED,
	JOB_URL,
	DATE_POSTED,
	DATE_RETRIEVED,
	IS_ACTIVE,
	EMPLOYMENT_STATUS,
	DEPARTMENT,
	DETECTED_LANGUAGE,
	LANGUAGE_CONFIDENCE,
	IS_ENGLISH,
	LANGUAGE_DETECTION_METHOD,
	SALARY_MIN,
	SALARY_MAX,
	SALARY_CURRENCY,
	SALARY_PERIOD,
	SALARY_CONFIDENCE,
	MIN_YEARS_EXPERIENCE,
	MAX_YEARS_EXPERIENCE,
	EXPERIENCE_LEVEL,
	EDUCATION_REQUIREMENTS,
	PROGRAMMING_LANGUAGES,
	DATABASES,
	CLOUD_PLATFORMS,
	FRAMEWORKS,
	TOOLS,
	SOFT_SKILLS,
	WORK_TYPE,
	REMOTE_FLEXIBILITY,
	TRAVEL_REQUIREMENTS,
	OFFICE_LOCATIONS,
	PRIMARY_KEYWORDS,
	INDUSTRY_KEYWORDS,
	ROLE_TYPE_KEYWORDS,
	COMPANY_STAGE_KEYWORDS,
	JOB_FAMILY,
	JOB_SUB_FAMILY,
	PLATFORM_SPECIFIC_DATA,
	TRANSFORMATION_TIMESTAMP,
	DATA_QUALITY_SCORE,
	EXTRACTION_CONFIDENCE_AVG,
	KEYWORD_QUALITY_SCORE,
	SOURCE_RAW_TABLE,
	RAW_DATA,
	PARTITION_DATE
) as
SELECT * FROM jobs_unified
WHERE date_posted >= CURRENT_DATE - 30
AND is_active = TRUE;

-- JOBS_WITH_SALARY
-- (Definitely need to use downstream tables for more accurate salary data)
create or replace view BETTERJOBS_DB.STAGE.JOBS_WITH_SALARY(
	JOB_ID,
	COMPANY_ID,
	PLATFORM,
	JOB_TITLE_CLEAN,
	JOB_DESCRIPTION_CLEAN,
	COMPANY_NAME_CLEAN,
	LOCATION_STANDARDIZED,
	JOB_URL,
	DATE_POSTED,
	DATE_RETRIEVED,
	IS_ACTIVE,
	EMPLOYMENT_STATUS,
	DEPARTMENT,
	DETECTED_LANGUAGE,
	LANGUAGE_CONFIDENCE,
	IS_ENGLISH,
	LANGUAGE_DETECTION_METHOD,
	SALARY_MIN,
	SALARY_MAX,
	SALARY_CURRENCY,
	SALARY_PERIOD,
	SALARY_CONFIDENCE,
	MIN_YEARS_EXPERIENCE,
	MAX_YEARS_EXPERIENCE,
	EXPERIENCE_LEVEL,
	EDUCATION_REQUIREMENTS,
	PROGRAMMING_LANGUAGES,
	DATABASES,
	CLOUD_PLATFORMS,
	FRAMEWORKS,
	TOOLS,
	SOFT_SKILLS,
	WORK_TYPE,
	REMOTE_FLEXIBILITY,
	TRAVEL_REQUIREMENTS,
	OFFICE_LOCATIONS,
	PRIMARY_KEYWORDS,
	INDUSTRY_KEYWORDS,
	ROLE_TYPE_KEYWORDS,
	COMPANY_STAGE_KEYWORDS,
	JOB_FAMILY,
	JOB_SUB_FAMILY,
	PLATFORM_SPECIFIC_DATA,
	TRANSFORMATION_TIMESTAMP,
	DATA_QUALITY_SCORE,
	EXTRACTION_CONFIDENCE_AVG,
	KEYWORD_QUALITY_SCORE,
	SOURCE_RAW_TABLE,
	RAW_DATA,
	PARTITION_DATE
) as
SELECT * FROM jobs_unified
WHERE salary_min IS NOT NULL OR salary_max IS NOT NULL;



-- JOB_LOCATIONS_COVERAGE
create or replace view BETTERJOBS_DB.STAGE.JOB_LOCATIONS_COVERAGE(
	TOTAL_JOBS,
	JOBS_WITH_LOCATIONS,
	COVERAGE_PERCENTAGE,
	AVG_LOCATIONS_PER_JOB
) as
SELECT
    COUNT(DISTINCT ju.JOB_UID) as TOTAL_JOBS,
    COUNT(DISTINCT jlb.JOB_UID) as JOBS_WITH_LOCATIONS,
    ROUND((COUNT(DISTINCT jlb.JOB_UID)::FLOAT / COUNT(DISTINCT ju.JOB_UID)) * 100, 2) as COVERAGE_PERCENTAGE,
    AVG(locations_per_job.LOCATION_COUNT) as AVG_LOCATIONS_PER_JOB
FROM JOBS_UNIFIED ju
LEFT JOIN JOB_LOCATIONS_BRIDGE jlb ON ju.JOB_UID = jlb.JOB_UID
LEFT JOIN (
    SELECT JOB_UID, COUNT(*) as LOCATION_COUNT
    FROM JOB_LOCATIONS_BRIDGE
    GROUP BY JOB_UID
) locations_per_job ON ju.JOB_UID = locations_per_job.JOB_UID;



-- JOB_SKILLS_COVERAGE
create or replace view BETTERJOBS_DB.STAGE.JOB_SKILLS_COVERAGE(
	TOTAL_JOBS,
	JOBS_WITH_SKILLS,
	COVERAGE_PERCENTAGE,
	AVG_SKILLS_PER_JOB
) as
SELECT
    COUNT(DISTINCT ju.JOB_UID) as TOTAL_JOBS,
    COUNT(DISTINCT jsb.JOB_UID) as JOBS_WITH_SKILLS,
    ROUND((COUNT(DISTINCT jsb.JOB_UID)::FLOAT / COUNT(DISTINCT ju.JOB_UID)) * 100, 2) as COVERAGE_PERCENTAGE,
    AVG(skills_per_job.SKILL_COUNT) as AVG_SKILLS_PER_JOB
FROM JOBS_UNIFIED ju
LEFT JOIN JOB_SKILLS_BRIDGE jsb ON ju.JOB_UID = jsb.JOB_UID
LEFT JOIN (
    SELECT JOB_UID, COUNT(*) as SKILL_COUNT
    FROM JOB_SKILLS_BRIDGE
    GROUP BY JOB_UID
) skills_per_job ON ju.JOB_UID = skills_per_job.JOB_UID;



-- KEYWORDS_RAW_EXTRACTION
create or replace view BETTERJOBS_DB.STAGE.KEYWORDS_RAW_EXTRACTION(
	JOB_UID,
	KEYWORD_SOURCE,
	KEYWORD_TYPE,
	KEYWORD_TEXT_RAW,
	KEYWORD_TEXT_ORIGINAL
) as
        WITH INDUSTRY_KEYWORDS_EXPLODED AS (
            -- Extract industry classification keywords from array
            SELECT
                jle.JOB_UID,
                'industry_keywords' as KEYWORD_SOURCE,
                'industry' as KEYWORD_TYPE,
                TRIM(LOWER(KEYWORD.VALUE::STRING)) as KEYWORD_TEXT_RAW,
                KEYWORD.VALUE::STRING as KEYWORD_TEXT_ORIGINAL
            FROM BETTERJOBS_DB.STAGE.JOBS_LLM_ENRICHED jle,
            LATERAL FLATTEN(input => jle.INDUSTRY_KEYWORDS) KEYWORD
            WHERE jle.INDUSTRY_KEYWORDS IS NOT NULL
              AND IS_ARRAY(jle.INDUSTRY_KEYWORDS)
              AND ARRAY_SIZE(jle.INDUSTRY_KEYWORDS) > 0
              AND KEYWORD.VALUE IS NOT NULL
              AND LENGTH(TRIM(KEYWORD.VALUE::STRING)) > 1
              AND LOWER(TRIM(KEYWORD.VALUE::STRING)) NOT IN ('null', 'none', 'n/a', '')
        ),

        ROLE_TYPE_EXPLODED AS (
            -- Extract role type from single string value (not an array)
            SELECT
                jle.JOB_UID,
                'role_type' as KEYWORD_SOURCE,
                'role_type' as KEYWORD_TYPE,
                TRIM(LOWER(jle.ROLE_TYPE)) as KEYWORD_TEXT_RAW,
                jle.ROLE_TYPE as KEYWORD_TEXT_ORIGINAL
            FROM BETTERJOBS_DB.STAGE.JOBS_LLM_ENRICHED jle
            WHERE jle.ROLE_TYPE IS NOT NULL
              AND LENGTH(TRIM(jle.ROLE_TYPE)) > 1
              AND LOWER(TRIM(jle.ROLE_TYPE)) NOT IN ('null', 'none', 'n/a', '')
        )

        SELECT * FROM INDUSTRY_KEYWORDS_EXPLODED
        UNION ALL
        SELECT * FROM ROLE_TYPE_EXPLODED;



-- LOCATIONS_ANALYSIS
create or replace view BETTERJOBS_DB.STAGE.LOCATIONS_ANALYSIS(
	LOCATION_NAME,
	CITY,
	STATE_PROVINCE,
	COUNTRY,
	LOCATION_TYPE,
	FREQUENCY,
	PLATFORMS,
	AVG_CONFIDENCE,
	IS_REMOTE_FRIENDLY,
	IS_MAJOR_TECH_HUB,
	TOTAL_MARKET_FREQUENCY
) as
SELECT
    ln.LOCATION_NAME,
    ln.CITY,
    ln.STATE_PROVINCE,
    ln.COUNTRY,
    ln.LOCATION_TYPE,
    COUNT(DISTINCT jlb.JOB_UID) as FREQUENCY,
    ARRAY_AGG(DISTINCT j.PLATFORM) as PLATFORMS,
    AVG(jlb.OVERALL_CONFIDENCE) as AVG_CONFIDENCE,
    ln.IS_REMOTE_FRIENDLY,
    ln.IS_MAJOR_TECH_HUB,
    ln.FREQUENCY_COUNT as TOTAL_MARKET_FREQUENCY
FROM LOCATIONS_NORMALIZED ln
LEFT JOIN JOB_LOCATIONS_BRIDGE jlb ON ln.LOCATION_ID = jlb.LOCATION_ID
LEFT JOIN JOBS_UNIFIED j ON jlb.JOB_UID = j.JOB_UID
WHERE j.IS_ENGLISH = TRUE OR j.IS_ENGLISH IS NULL
GROUP BY ln.LOCATION_NAME, ln.CITY, ln.STATE_PROVINCE, ln.COUNTRY, ln.LOCATION_TYPE,
         ln.IS_REMOTE_FRIENDLY, ln.IS_MAJOR_TECH_HUB, ln.FREQUENCY_COUNT
ORDER BY FREQUENCY DESC;


-- PLATFORM_SUMMARY
create or replace view BETTERJOBS_DB.STAGE.PLATFORM_SUMMARY(
	PLATFORM,
	TOTAL_JOBS,
	ENGLISH_JOBS,
	JOBS_WITH_SALARY,
	AVG_QUALITY_SCORE,
	EARLIEST_JOB,
	LATEST_JOB
) as
SELECT
    platform,
    COUNT(*) as total_jobs,
    COUNT(CASE WHEN is_english = TRUE THEN 1 END) as english_jobs,
    COUNT(CASE WHEN salary_min IS NOT NULL THEN 1 END) as jobs_with_salary,
    AVG(data_quality_score) as avg_quality_score,
    MIN(date_posted) as earliest_job,
    MAX(date_posted) as latest_job
FROM jobs_unified
GROUP BY platform;


-- SKILLS_ANALYSIS
create or replace view BETTERJOBS_DB.STAGE.SKILLS_ANALYSIS(
	SKILL_NAME,
	SKILL_CATEGORY,
	SKILL_SUBCATEGORY,
	FREQUENCY,
	PLATFORMS,
	AVG_CONFIDENCE,
	TREND_DIRECTION,
	TOTAL_MARKET_FREQUENCY
) as
SELECT
    sn.SKILL_NAME,
    sn.SKILL_CATEGORY,
    sn.SKILL_SUBCATEGORY,
    COUNT(DISTINCT jsb.JOB_UID) as FREQUENCY,
    ARRAY_AGG(DISTINCT j.PLATFORM) as PLATFORMS,
    AVG(jsb.OVERALL_CONFIDENCE) as AVG_CONFIDENCE,
    sn.TREND_DIRECTION,
    sn.FREQUENCY_COUNT as TOTAL_MARKET_FREQUENCY
FROM SKILLS_NORMALIZED sn
LEFT JOIN JOB_SKILLS_BRIDGE jsb ON sn.SKILL_ID = jsb.SKILL_ID
LEFT JOIN JOBS_UNIFIED j ON jsb.JOB_UID = j.JOB_UID
WHERE j.IS_ENGLISH = TRUE OR j.IS_ENGLISH IS NULL
GROUP BY sn.SKILL_NAME, sn.SKILL_CATEGORY, sn.SKILL_SUBCATEGORY, sn.TREND_DIRECTION, sn.FREQUENCY_COUNT
ORDER BY FREQUENCY DESC;


-- SKILLS_QUALITY_REPORT
create or replace view BETTERJOBS_DB.STAGE.SKILLS_QUALITY_REPORT(
	SKILL_CATEGORY,
	TOTAL_SKILLS,
	HIGH_CONFIDENCE_SKILLS,
	LOW_CONFIDENCE_SKILLS,
	NEEDS_REVIEW,
	AVG_CONFIDENCE,
	AVG_FREQUENCY
) as
SELECT
    SKILL_CATEGORY,
    COUNT(*) as TOTAL_SKILLS,
    COUNT(CASE WHEN CONFIDENCE_SCORE >= 0.8 THEN 1 END) as HIGH_CONFIDENCE_SKILLS,
    COUNT(CASE WHEN CONFIDENCE_SCORE < 0.5 THEN 1 END) as LOW_CONFIDENCE_SKILLS,
    COUNT(CASE WHEN MANUAL_REVIEW_FLAG THEN 1 END) as NEEDS_REVIEW,
    AVG(CONFIDENCE_SCORE) as AVG_CONFIDENCE,
    AVG(FREQUENCY_COUNT) as AVG_FREQUENCY
FROM SKILLS_NORMALIZED
GROUP BY SKILL_CATEGORY
ORDER BY TOTAL_SKILLS DESC;


-- SKILLS_RAW_EXTRACTION
create or replace view BETTERJOBS_DB.STAGE.SKILLS_RAW_EXTRACTION(
	JOB_UID,
	SKILL_SOURCE,
	SKILL_CATEGORY,
	SKILL_NAME_RAW,
	SKILL_NAME_ORIGINAL
) as
        WITH         TECHNICAL_SKILLS_EXPLODED AS (
            -- Extract technical skills by category
            SELECT
                jle.JOB_UID,
                'technical_skills' as SKILL_SOURCE,
                SKILL_CATEGORY.KEY::STRING as SKILL_CATEGORY,
                TRIM(LOWER(SKILL_NAME.VALUE::STRING)) as SKILL_NAME_RAW,
                SKILL_NAME.VALUE::STRING as SKILL_NAME_ORIGINAL
            FROM BETTERJOBS_DB.STAGE.JOBS_LLM_ENRICHED jle,
            LATERAL FLATTEN(input => jle.TECHNICAL_SKILLS) SKILL_CATEGORY,
            LATERAL FLATTEN(input => SKILL_CATEGORY.VALUE) SKILL_NAME
            WHERE jle.TECHNICAL_SKILLS IS NOT NULL
              AND SKILL_CATEGORY.VALUE IS NOT NULL
              AND IS_ARRAY(SKILL_CATEGORY.VALUE)
              AND ARRAY_SIZE(SKILL_CATEGORY.VALUE) > 0
              AND LENGTH(TRIM(SKILL_NAME.VALUE::STRING)) > 1
              AND LOWER(TRIM(SKILL_NAME.VALUE::STRING)) NOT IN ('null', 'none', 'n/a', '')
        ),

        SOFT_SKILLS_EXPLODED AS (
            -- Extract soft skills
            SELECT
                jle.JOB_UID,
                'soft_skills' as SKILL_SOURCE,
                'soft' as SKILL_CATEGORY,
                TRIM(LOWER(SKILL.VALUE::STRING)) as SKILL_NAME_RAW,
                SKILL.VALUE::STRING as SKILL_NAME_ORIGINAL
            FROM BETTERJOBS_DB.STAGE.JOBS_LLM_ENRICHED jle,
            LATERAL FLATTEN(input => jle.SOFT_SKILLS) SKILL
            WHERE jle.SOFT_SKILLS IS NOT NULL
              AND SKILL.VALUE IS NOT NULL
              AND LENGTH(TRIM(SKILL.VALUE::STRING)) > 1
              AND LOWER(TRIM(SKILL.VALUE::STRING)) NOT IN ('null', 'none', 'n/a', '')
        ),

        PRIMARY_KEYWORDS_EXPLODED AS (
            -- Extract primary keywords as skills
            SELECT
                jle.JOB_UID,
                'primary_keywords' as SKILL_SOURCE,
                'keyword' as SKILL_CATEGORY,
                TRIM(LOWER(KEYWORD.VALUE::STRING)) as SKILL_NAME_RAW,
                KEYWORD.VALUE::STRING as SKILL_NAME_ORIGINAL
            FROM BETTERJOBS_DB.STAGE.JOBS_LLM_ENRICHED jle,
            LATERAL FLATTEN(input => jle.PRIMARY_KEYWORDS) KEYWORD
            WHERE jle.PRIMARY_KEYWORDS IS NOT NULL
              AND KEYWORD.VALUE IS NOT NULL
              AND LENGTH(TRIM(KEYWORD.VALUE::STRING)) > 1
              AND LOWER(TRIM(KEYWORD.VALUE::STRING)) NOT IN ('null', 'none', 'n/a', '')
        )

        SELECT * FROM TECHNICAL_SKILLS_EXPLODED
        UNION ALL
        SELECT * FROM SOFT_SKILLS_EXPLODED
        UNION ALL
        SELECT * FROM PRIMARY_KEYWORDS_EXPLODED;


-- SKILL_CATEGORY_PATTERNS_ANALYSIS
create or replace view BETTERJOBS_DB.STAGE.SKILL_CATEGORY_PATTERNS_ANALYSIS(
	SKILL_CATEGORY,
	TOTAL_PATTERNS,
	ACTIVE_PATTERNS,
	INACTIVE_PATTERNS,
	AVG_CONFIDENCE,
	MIN_CONFIDENCE,
	MAX_CONFIDENCE,
	ACTIVE_PATTERN_LIST
) as
SELECT
    SKILL_CATEGORY,
    COUNT(*) as TOTAL_PATTERNS,
    COUNT(CASE WHEN IS_ACTIVE = TRUE THEN 1 END) as ACTIVE_PATTERNS,
    COUNT(CASE WHEN IS_ACTIVE = FALSE THEN 1 END) as INACTIVE_PATTERNS,
    AVG(CONFIDENCE_SCORE) as AVG_CONFIDENCE,
    MIN(CONFIDENCE_SCORE) as MIN_CONFIDENCE,
    MAX(CONFIDENCE_SCORE) as MAX_CONFIDENCE,
    ARRAY_AGG(CASE WHEN IS_ACTIVE = TRUE THEN PATTERN END) as ACTIVE_PATTERN_LIST
FROM SKILL_CATEGORY_PATTERNS
GROUP BY SKILL_CATEGORY
ORDER BY TOTAL_PATTERNS DESC;


-- TOP_LOCATIONS_BY_TYPE
create or replace view BETTERJOBS_DB.STAGE.TOP_LOCATIONS_BY_TYPE(
	LOCATION_TYPE,
	LOCATION_NAME,
	CITY,
	STATE_PROVINCE,
	COUNTRY,
	FREQUENCY_COUNT,
	IS_MAJOR_TECH_HUB,
	CONFIDENCE_SCORE,
	RANK_IN_TYPE
) as
SELECT
    LOCATION_TYPE,
    LOCATION_NAME,
    CITY,
    STATE_PROVINCE,
    COUNTRY,
    FREQUENCY_COUNT,
    IS_MAJOR_TECH_HUB,
    CONFIDENCE_SCORE,
    ROW_NUMBER() OVER (PARTITION BY LOCATION_TYPE ORDER BY FREQUENCY_COUNT DESC) as RANK_IN_TYPE
FROM LOCATIONS_NORMALIZED
WHERE CONFIDENCE_SCORE >= 0.8
ORDER BY LOCATION_TYPE, RANK_IN_TYPE;


-- TOP_SKILLS_BY_CATEGORY
create or replace view BETTERJOBS_DB.STAGE.TOP_SKILLS_BY_CATEGORY(
	SKILL_CATEGORY,
	SKILL_NAME,
	FREQUENCY_COUNT,
	TREND_DIRECTION,
	CONFIDENCE_SCORE,
	RANK_IN_CATEGORY
) as
SELECT
    SKILL_CATEGORY,
    SKILL_NAME,
    FREQUENCY_COUNT,
    TREND_DIRECTION,
    CONFIDENCE_SCORE,
    ROW_NUMBER() OVER (PARTITION BY SKILL_CATEGORY ORDER BY FREQUENCY_COUNT DESC) as RANK_IN_CATEGORY
FROM SKILLS_NORMALIZED
WHERE CONFIDENCE_SCORE >= 0.8
ORDER BY SKILL_CATEGORY, RANK_IN_CATEGORY;


-- US_STATES_LOOKUP
create or replace view BETTERJOBS_DB.STAGE.US_STATES_LOOKUP AS
SELECT STATE_NAME_FULL as STATE_NAME, COUNTRY FROM BETTERJOBS_DB.STAGE.US_STATES_MAPPING
UNION ALL
SELECT STATE_ABBREVIATION as STATE_NAME, COUNTRY FROM BETTERJOBS_DB.STAGE.US_STATES_MAPPING;

-- Create lookup views for efficient country detection
create or replace view BETTERJOBS_DB.STAGE.COUNTRIES_LOOKUP AS
SELECT COUNTRY_NAME_COMMON as COUNTRY_NAME, COUNTRY_CODE_ISO2, REGION, IS_MAJOR_TECH_HUB FROM COUNTRIES_MAPPING
UNION ALL
SELECT COUNTRY_NAME_OFFICIAL as COUNTRY_NAME, COUNTRY_CODE_ISO2, REGION, IS_MAJOR_TECH_HUB FROM COUNTRIES_MAPPING
WHERE COUNTRY_NAME_OFFICIAL != COUNTRY_NAME_COMMON;

-- Create a comprehensive lookup that includes both countries and US states for parsing logic
create or replace view BETTERJOBS_DB.STAGE.LOCATION_PARSING_LOOKUP AS
-- US States (for state detection)
SELECT
    STATE_NAME as LOCATION_NAME,
    'US_STATE' as LOCATION_TYPE,
    'United States' as COUNTRY,
    NULL as REGION,
    FALSE as IS_MAJOR_TECH_HUB
FROM BETTERJOBS_DB.STAGE.US_STATES_LOOKUP
UNION ALL
-- Countries (for country detection)
SELECT
    COUNTRY_NAME as LOCATION_NAME,
    'COUNTRY' as LOCATION_TYPE,
    COUNTRY_NAME as COUNTRY,
    REGION,
    IS_MAJOR_TECH_HUB
FROM BETTERJOBS_DB.STAGE.COUNTRIES_LOOKUP;