CREATE TABLE ANALYTICS.MARKET_WEEKLY_SUMMARY (
    SUMMARY_KEY STRING PRIMARY KEY,
    WEEK_ENDING_DATE DATE,
    WEEK_KEY STRING,                        -- YYYY-WW format

    -- Core Market Metrics
    TOTAL_JOBS_POSTED INTEGER,
    TOTAL_ACTIVE_JOBS INTEGER,
    NEW_JOBS_POSTED INTEGER,

    -- Velocity Metrics
    WEEK_OVER_WEEK_GROWTH_RATE FLOAT,
    POSTING_VELOCITY_DAILY FLOAT,

    -- Salary Intelligence
    MEDIAN_SALARY_ALL_ROLES NUMBER,
    AVG_SALARY_ALL_ROLES NUMBER,

    -- Work Arrangement Trends
    REMOTE_WORK_PERCENTAGE FLOAT,
    HYBRID_WORK_PERCENTAGE FLOAT,
    ONSITE_WORK_PERCENTAGE FLOAT,

    -- Quality Metrics
    SAMPLE_SIZE INTEGER,
    DATA_QUALITY_SCORE FLOAT,

    -- Audit Fields
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
) CLUSTER BY (WEEK_KEY);