CREATE TABLE IF NOT EXISTS BETTERJOBS_DB.ANALYTICS.JOB_EXPERIENCE_BRIDGE (
    EXPERIENCE_BRIDGE_KEY STRING PRIMARY KEY,
    JOB_POSTING_KEY STRING NOT NULL,
    EXPERIENCE_KEY STRING NOT NULL,
    EXPERIENCE_WEIGHT FLOAT DEFAULT 1.0,
    IS_PRIMARY_REQUIREMENT BOOLEAN DEFAULT FALSE,
    EXTRACTION_CONFIDENCE FLOAT,
    TECHNOLOGY_CONTEXT STRING,
    PROCESSING_METHOD STRING DEFAULT 'llm_auto',
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (JOB_POSTING_KEY) REFERENCES BETTERJOBS_DB.ANALYTICS.FACT_JOB_POSTINGS(JOB_POSTING_KEY),
    FOREIGN KEY (EXPERIENCE_KEY) REFERENCES BETTERJOBS_DB.ANALYTICS.DIM_EXPERIENCE(EXPERIENCE_KEY)
) CLUSTER BY (JOB_POSTING_KEY, EXPERIENCE_KEY);