CREATE TABLE ANALYTICS.JOB_SKILLS_BRIDGE (
    SKILLS_BRIDGE_KEY STRING PRIMARY KEY,
    JOB_POSTING_KEY STRING NOT NULL,
    SKILL_KEY STRING NOT NULL,

    /* Relationship attributes */
    SKILL_WEIGHT FLOAT DEFAULT 1.0,
    IS_PRIMARY_SKILL BOOLEAN DEFAULT FALSE,
    IS_REQUIRED_SKILL BOOLEAN DEFAULT TRUE,

    /* Quality & metadata */
    EXTRACTION_CONFIDENCE FLOAT,
    SKILL_CATEGORY STRING,
    TECHNOLOGY_CONTEXT STRING,
    YEARS_EXPERIENCE_MIN INTEGER,
    YEARS_EXPERIENCE_MAX INTEGER,
    PROCESSING_METHOD STRING DEFAULT 'llm_auto',

    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,

    /* Foreign key constraints */
    FOREIGN KEY (JOB_POSTING_KEY) REFERENCES ANALYTICS.FACT_JOB_POSTINGS(JOB_POSTING_KEY),
    FOREIGN KEY (SKILL_KEY) REFERENCES ANALYTICS.DIM_SKILLS(SKILL_KEY)
) CLUSTER BY (JOB_POSTING_KEY, SKILL_KEY);