CREATE TABLE ANALYTICS.SKILLS_TREND_ANALYSIS (
    ANALYSIS_KEY STRING PRIMARY KEY,
    ANALYSIS_DATE DATE,
    SKILL_KEY STRING,
    WEEK_KEY STRING,                        -- YYYY-WW format

    -- Current Demand Metrics
    JOBS_REQUIRING_SKILL INTEGER,
    TOTAL_JOBS_ANALYZED INTEGER,
    MARKET_PENETRATION_RATE FLOAT,          -- Percentage of jobs requiring this skill
    DEMAND_RANK_OVERALL INTEGER,

    -- Growth Metrics
    DEMAND_GROWTH_WEEKLY FLOAT,
    DEMAND_GROWTH_MONTHLY FLOAT,

    -- Ranking Changes
    RANK_CHANGE_WEEKLY INTEGER,
    RANK_CHANGE_MONTHLY INTEGER,

    -- Salary Impact
    AVERAGE_SALARY_WITH_SKILL NUMBER,
    SALARY_PREMIUM_PERCENTAGE FLOAT,

    -- Work Arrangement
    REMOTE_AVAILABILITY_RATE FLOAT,         -- Percentage of remote jobs with this skill

    -- Seniority Distribution
    ENTRY_LEVEL_DEMAND INTEGER,
    MID_LEVEL_DEMAND INTEGER,
    SENIOR_LEVEL_DEMAND INTEGER,

    -- Quality Metrics
    SAMPLE_SIZE INTEGER,
    DATA_QUALITY_SCORE FLOAT,

    -- Audit Fields
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
) PARTITION BY (ANALYSIS_DATE)
CLUSTER BY (ANALYSIS_DATE, SKILL_KEY);