CREATE TABLE ANALYTICS.COMPANY_HIRING_INTELLIGENCE (
    INTELLIGENCE_KEY STRING PRIMARY KEY,
    ANALYSIS_DATE DATE,
    COMPANY_KEY STRING,
    WEEK_KEY STRING,                        -- YYYY-WW format

    -- Hiring Velocity
    JOBS_POSTED_LAST_7_DAYS INTEGER,
    JOBS_POSTED_LAST_30_DAYS INTEGER,
    CURRENT_JOB_POSTINGS INTEGER,

    -- Growth Indicators
    HIRING_VELOCITY_TREND STRING,           -- 'ACCELERATING', 'STABLE', 'DECELERATING'
    WEEK_OVER_WEEK_GROWTH_RATE FLOAT,

    -- Compensation Strategy
    SALARY_TRANSPARENCY_RATE FLOAT,         -- Percentage of jobs with salary disclosed
    AVG_SALARY_OFFERED NUMBER,

    -- Role Distribution
    ENTRY_VS_SENIOR_RATIO FLOAT,
    TECHNICAL_VS_BUSINESS_RATIO FLOAT,
    REMOTE_JOB_PERCENTAGE FLOAT,

    -- Work Arrangement Policy
    REMOTE_WORK_POLICY STRING,              -- 'FULL_REMOTE', 'HYBRID', 'ONSITE'

    -- Market Position
    HIRING_RANK_IN_INDUSTRY INTEGER,
    HIRING_COMPETITIVENESS_SCORE FLOAT,

    -- Quality Metrics
    SAMPLE_SIZE INTEGER,
    DATA_COMPLETENESS_SCORE FLOAT,

    -- Audit Fields
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
) PARTITION BY (ANALYSIS_DATE)
CLUSTER BY (ANALYSIS_DATE, COMPANY_KEY);