CREATE TABLE ANALYTICS.DIM_JOB_FAMILY (
    JOB_FAMILY_KEY STRING PRIMARY KEY,

    -- Core LLM-Extracted Fields (from STAGE.JOBS_LLM_ENRICHED)
    JOB_FAMILY STRING,              -- Direct from STAGE.JOBS_LLM_ENRICHED.JOB_FAMILY
    JOB_SUB_FAMILY STRING,          -- Direct from STAGE.JOBS_LLM_ENRICHED.JOB_SUB_FAMILY
    SENIORITY_LEVEL STRING,         -- Direct from STAGE.JOBS_LLM_ENRICHED.SENIORITY_LEVEL
    ROLE_TYPE STRING,               -- Direct from STAGE.JOBS_LLM_ENRICHED.ROLE_TYPE

    -- Simple Derived Fields
    SENIORITY_ORDER INTEGER,        -- Numeric ordering from SENIORITY_LEVEL text (1-7)
    IS_MANAGEMENT_ROLE BOOLEAN,     -- Derived from ROLE_TYPE analysis

    -- Audit Fields
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
) CLUSTER BY (JOB_FAMILY, SENIORITY_LEVEL);