CREATE TABLE ANALYTICS.DIM_EXPERIENCE (
    EXPERIENCE_KEY STRING PRIMARY KEY,
    EXPERIENCE_ID STRING,              -- FK to STAGE.EXPERIENCE_NORMALIZED.EXPERIENCE_ID
    EXPERIENCE_NAME STRING,

    -- Experience Classification (from STAGE.EXPERIENCE_NORMALIZED)
    EXPERIENCE_CATEGORY STRING,        -- From STAGE.EXPERIENCE_NORMALIZED.EXPERIENCE_CATEGORY
    MIN_YEARS_REQUIRED INTEGER,        -- From STAGE.EXPERIENCE_NORMALIZED.MIN_YEARS_REQUIRED
    MAX_YEARS_REQUIRED INTEGER,        -- From STAGE.EXPERIENCE_NORMALIZED.MAX_YEARS_REQUIRED
    SENIORITY_ORDER INTEGER,           -- From STAGE.EXPERIENCE_NORMALIZED.SENIORITY_ORDER
    EXPERIENCE_DESCRIPTION STRING,     -- From STAGE.EXPERIENCE_NORMALIZED.EXPERIENCE_DESCRIPTION

    -- Market Intelligence (from STAGE.EXPERIENCE_NORMALIZED)
    MARKET_FREQUENCY INTEGER,          -- From STAGE.EXPERIENCE_NORMALIZED.MARKET_FREQUENCY
    CONFIDENCE_SCORE FLOAT,            -- From STAGE.EXPERIENCE_NORMALIZED.CONFIDENCE_SCORE

    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
) CLUSTER BY (EXPERIENCE_CATEGORY, SENIORITY_ORDER);