CREATE TABLE ANALYTICS.FACT_JOB_POSTINGS (
    -- Surrogate Key
    JOB_POSTING_KEY STRING PRIMARY KEY,  -- One key per unique job posting

    -- Dimension Keys
    DATE_POSTED_KEY STRING,              -- When job was first posted
    COMPANY_KEY STRING,
    LOCATION_KEY STRING,
    JOB_FAMILY_KEY STRING,
    PLATFORM_KEY STRING,
    EXPERIENCE_KEY STRING,               -- FK to DIM_EXPERIENCE
    KEYWORD_KEY STRING,                  -- FK to DIM_KEYWORDS (primary keyword for job)

    -- Degenerate Dimensions
    JOB_UID STRING,                      -- Natural key from STAGE.JOBS_UNIFIED.JOB_UID
    JOB_TITLE STRING,                    -- From STAGE.JOBS_UNIFIED.JOB_TITLE_CLEAN
    POSTING_URL STRING,                  -- From STAGE.JOBS_UNIFIED.JOB_URL

    -- Salary Measures (from STAGE.JOBS_LLM_ENRICHED)
    SALARY_MIN NUMBER,                   -- From STAGE.JOBS_LLM_ENRICHED.SALARY_MIN
    SALARY_MAX NUMBER,                   -- From STAGE.JOBS_LLM_ENRICHED.SALARY_MAX
    SALARY_CURRENCY STRING,              -- From STAGE.JOBS_LLM_ENRICHED.SALARY_CURRENCY
    SALARY_PERIOD STRING,                -- From STAGE.JOBS_LLM_ENRICHED.SALARY_PERIOD

    -- Experience Measures (from STAGE.JOBS_LLM_ENRICHED)
    EXPERIENCE_MIN_YEARS NUMBER,         -- From STAGE.JOBS_LLM_ENRICHED.MIN_YEARS_EXPERIENCE
    EXPERIENCE_MAX_YEARS NUMBER,         -- From STAGE.JOBS_LLM_ENRICHED.MAX_YEARS_EXPERIENCE
    EXPERIENCE_LEVEL STRING,             -- From STAGE.JOBS_LLM_ENRICHED.EXPERIENCE_LEVEL

    -- Quality and Confidence Measures
    SALARY_CONFIDENCE FLOAT,             -- From STAGE.JOBS_LLM_ENRICHED.SALARY_CONFIDENCE
    LLM_OVERALL_CONFIDENCE FLOAT,        -- From STAGE.JOBS_LLM_ENRICHED.LLM_OVERALL_CONFIDENCE
    DATA_QUALITY_SCORE FLOAT,            -- From STAGE.JOBS_UNIFIED.DATA_QUALITY_SCORE

    -- Job Classification (from STAGE.JOBS_LLM_ENRICHED)
    JOB_FAMILY STRING,                   -- From STAGE.JOBS_LLM_ENRICHED.JOB_FAMILY
    JOB_SUB_FAMILY STRING,               -- From STAGE.JOBS_LLM_ENRICHED.JOB_SUB_FAMILY
    SENIORITY_LEVEL STRING,              -- From STAGE.JOBS_LLM_ENRICHED.SENIORITY_LEVEL

    -- Work Arrangement (from STAGE.JOBS_LLM_ENRICHED)
    WORK_TYPE STRING,                    -- From STAGE.JOBS_LLM_ENRICHED.WORK_TYPE
    REMOTE_FLEXIBILITY STRING,           -- From STAGE.JOBS_LLM_ENRICHED.REMOTE_FLEXIBILITY

    -- Boolean Flags (from STAGE tables)
    IS_ACTIVE_POSTING BOOLEAN,           -- From STAGE.JOBS_UNIFIED.IS_ACTIVE
    IS_EQUITY_MENTIONED BOOLEAN,         -- From STAGE.JOBS_LLM_ENRICHED.EQUITY_MENTIONED
    IS_BONUS_MENTIONED BOOLEAN,          -- From STAGE.JOBS_LLM_ENRICHED.BONUS_MENTIONED
    LLM_NEEDS_MANUAL_REVIEW BOOLEAN,     -- From STAGE.JOBS_LLM_ENRICHED.LLM_NEEDS_MANUAL_REVIEW

    -- Important Dates
    FIRST_POSTED_DATE DATE,              -- From STAGE.JOBS_UNIFIED.DATE_POSTED
    DATE_RETRIEVED DATE,                 -- From STAGE.JOBS_UNIFIED.DATE_RETRIEVED

    -- Audit Fields
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,

    -- Partitioning by posting month for query performance
    PARTITION_DATE DATE                  -- DATE_TRUNC('month', first_posted_date)
) PARTITION BY (PARTITION_DATE)
CLUSTER BY (DATE_POSTED_KEY, COMPANY_KEY, LOCATION_KEY, JOB_FAMILY_KEY);