CREATE TABLE ANALYTICS.DIM_KEYWORDS (
    KEYWORD_KEY STRING PRIMARY KEY,
    KEYWORD_ID STRING,                 -- FK to STAGE.KEYWORDS_NORMALIZED.KEYWORD_ID
    KEYWORD_TEXT STRING,
    KEYWORD_TEXT_CLEAN STRING,

    -- Keyword Classification (from STAGE.KEYWORDS_NORMALIZED)
    KEYWORD_TYPE STRING,               -- From STAGE.KEYWORDS_NORMALIZED.KEYWORD_TYPE
    KEYWORD_CATEGORY STRING,           -- From STAGE.KEYWORDS_NORMALIZED.KEYWORD_CATEGORY
    CANONICAL_FORM STRING,             -- From STAGE.KEYWORDS_NORMALIZED.CANONICAL_FORM
    ORIGINAL_VARIANTS VARIANT,         -- From STAGE.KEYWORDS_NORMALIZED.ORIGINAL_VARIANTS

    -- Market Intelligence (from STAGE.KEYWORDS_NORMALIZED)
    FREQUENCY_COUNT INTEGER,           -- From STAGE.KEYWORDS_NORMALIZED.FREQUENCY_COUNT
    TREND_SCORE FLOAT,                 -- From STAGE.KEYWORDS_NORMALIZED.TREND_SCORE
    CONFIDENCE_SCORE FLOAT,            -- From STAGE.KEYWORDS_NORMALIZED.CONFIDENCE_SCORE
    APPROVED_BY_ADMIN BOOLEAN,         -- From STAGE.KEYWORDS_NORMALIZED.APPROVED_BY_ADMIN

    created_timestamp TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
) CLUSTER BY (keyword_type, keyword_category);