CREATE TABLE ANALYTICS.DIM_DATE (
    DATE_KEY STRING PRIMARY KEY,
    FULL_DATE DATE,

    -- Essential Date Attributes
    DAY_NAME STRING,
    DAY_OF_WEEK INTEGER,
    WEEK_BEGINNING_DATE DATE,
    WEEK_ENDING_DATE DATE,
    MONTH_NUMBER INTEGER,
    MONTH_NAME STRING,
    QUARTER_NUMBER INTEGER,
    YEAR_NUMBER INTEGER,

    -- Business Context
    IS_BUSINESS_DAY BOOLEAN,
    IS_WEEKEND BOOLEAN,

    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
) CLUSTER BY (FULL_DATE);