CREATE TABLE IF NOT EXISTS BETTERJOBS_DB.ANALYTICS.JOB_KEYWORDS_BRIDGE (
    KEYWORDS_BRIDGE_KEY STRING PRIMARY KEY,
    JOB_POSTING_KEY STRING NOT NULL,
    KEYWORD_KEY STRING NOT NULL,
    KEYWORD_WEIGHT FLOAT DEFAULT 1.0,
    KEYWORD_POSITION INTEGER,
    EXTRACTION_CONFIDENCE FLOAT,
    KEYWORD_TYPE STRING,
    KEYWORD_CATEGORY STRING,
    PROCESSING_METHOD STRING DEFAULT 'llm_auto',
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (JOB_POSTING_KEY) REFERENCES BETTERJOBS_DB.ANALYTICS.FACT_JOB_POSTINGS(JOB_POSTING_KEY),
    FOREIGN KEY (KEYWORD_KEY) REFERENCES BETTERJOBS_DB.ANALYTICS.DIM_KEYWORDS(KEYWORD_KEY)
) CLUSTER BY (JOB_POSTING_KEY, KEYWORD_KEY);