CREATE TABLE ANALYTICS.FACT_JOB_POSTINGS (
    -- Surrogate Key
    JOB_POSTING_KEY STRING PRIMARY KEY,  -- One key per unique job posting

    -- Dimension Keys
    DATE_POSTED_KEY STRING,              -- When job was first posted
    COMPANY_KEY STRING,
    LOCATION_KEY STRING,
    JOB_FAMILY_KEY STRING,
    PLATFORM_KEY STRING,
    KEYWORD_KEY STRING,                  -- FK to DIM_KEYWORDS (primary keyword for job)
    SALARY_KEY STRING,                   -- FK to DIM_SALARY (normalized salary data)

    -- Degenerate Dimensions
    JOB_UID STRING,                      -- Natural key from STAGE.JOBS_UNIFIED.JOB_UID
    JOB_TITLE STRING,                    -- From STAGE.JOBS_UNIFIED.JOB_TITLE_CLEAN
    POSTING_URL STRING,                  -- From STAGE.JOBS_UNIFIED.JOB_URL

    -- Salary Measures (ENHANCEMENT-022: Normalized Annual USD for Performance)
    SALARY_MIN_ANNUAL_USD NUMBER,       -- From DIM_SALARY.SALARY_MIN_ANNUAL_USD (denormalized for performance)
    SALARY_MAX_ANNUAL_USD NUMBER,       -- From DIM_SALARY.SALARY_MAX_ANNUAL_USD (denormalized for performance)
    SALARY_MIDPOINT_ANNUAL_USD NUMBER,  -- From DIM_SALARY.SALARY_MIDPOINT_ANNUAL_USD (denormalized for performance)

    -- Quality and Confidence Measures
    SALARY_CONFIDENCE FLOAT,             -- From STAGE.JOB_SALARY_BRIDGE.OVERALL_CONFIDENCE
    LLM_OVERALL_CONFIDENCE FLOAT,        -- From STAGE.JOBS_LLM_ENRICHED.LLM_OVERALL_CONFIDENCE
    DATA_QUALITY_SCORE FLOAT,            -- From STAGE.JOBS_UNIFIED.DATA_QUALITY_SCORE

    -- Job Classification (from STAGE.JOBS_LLM_ENRICHED)
    JOB_FAMILY STRING,                   -- From STAGE.JOBS_LLM_ENRICHED.JOB_FAMILY
    JOB_SUB_FAMILY STRING,               -- From STAGE.JOBS_LLM_ENRICHED.JOB_SUB_FAMILY
    SENIORITY_LEVEL STRING,              -- From STAGE.JOBS_LLM_ENRICHED.SENIORITY_LEVEL

    -- Work Arrangement (from STAGE.JOBS_LLM_ENRICHED)
    WORK_TYPE STRING,                    -- From STAGE.JOBS_LLM_ENRICHED.WORK_TYPE
    REMOTE_FLEXIBILITY STRING,           -- From STAGE.JOBS_LLM_ENRICHED.REMOTE_FLEXIBILITY

    -- Boolean Flags (from STAGE tables)
    IS_ACTIVE_POSTING BOOLEAN,           -- From STAGE.JOBS_UNIFIED.IS_ACTIVE
    IS_EQUITY_MENTIONED BOOLEAN,         -- From STAGE.JOBS_LLM_ENRICHED.EQUITY_MENTIONED
    IS_BONUS_MENTIONED BOOLEAN,          -- From STAGE.JOBS_LLM_ENRICHED.BONUS_MENTIONED
    LLM_NEEDS_MANUAL_REVIEW BOOLEAN,     -- From STAGE.JOBS_LLM_ENRICHED.LLM_NEEDS_MANUAL_REVIEW

    -- Important Dates
    FIRST_POSTED_DATE DATE,              -- From STAGE.JOBS_UNIFIED.DATE_POSTED
    DATE_RETRIEVED DATE,                 -- From STAGE.JOBS_UNIFIED.DATE_RETRIEVED

    -- Audit Fields
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,

    -- Partitioning by posting month for query performance
    PARTITION_DATE DATE                  -- DATE_TRUNC('month', first_posted_date)
) CLUSTER BY (PARTITION_DATE, DATE_POSTED_KEY, COMPANY_KEY, LOCATION_KEY, JOB_FAMILY_KEY);