CREATE TABLE IF NOT EXISTS BETTERJOBS_DB.ANALYTICS.DIM_SALARY CLUSTER BY (SALARY_MIDPOINT_ANNUAL_USD) (
    SALARY_KEY VARCHAR(16777216) NOT NULL,
    SALARY_ID VARCHAR(16777216),

    -- Human-readable description
    SALARY_RANGE_NAME VARCHAR(16777216),

    -- Original Values (Audit Trail)
    SALARY_MIN_ORIGINAL NUMBER,
    SALARY_MAX_ORIGINAL NUMBER,
    SALARY_PERIOD_ORIGINAL VARCHAR(16777216),
    SALARY_CURRENCY_ORIGINAL VARCHAR(16777216),

    -- Normalized Values (All Annual USD)
    SALARY_MIN_ANNUAL_USD NUMBER,
    SALARY_MAX_ANNUAL_USD NUMBER,
    SALARY_MIDPOINT_ANNUAL_USD NUMBER,
    NORMALIZATION_FACTOR FLOAT,

    -- Quality & Validation
    CONFIDENCE_SCORE FLOAT,
    OUTLIER_FLAG BOOLEAN DEFAULT FALSE,
    MANUAL_REVIEW_FLAG BOOLEAN DEFAULT FALSE,
    APPROVED_BY_ADMIN BOOLEAN DEFAULT FALSE,

    -- Market Intelligence
    FREQUENCY_COUNT NUMBER(38,0) DEFAULT 0,
    MARKET_PERCENTILE NUMBER(38,0),

    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SALARY_KEY)
);