create or replace TABLE BETTERJOBS_DB.RAW.MASTER_COMPANY_URLS_PROCESSING_LOG (
	FILE_PATH VARCHAR(16777216),
	FILE_HASH VARCHAR(16777216),
	FILE_SIZE NUMBER(38,0),
	FILE_MODIFIED_TIME TIMESTAMP_NTZ(9),
	PROCESSED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	RECORD_COUNT NUMBER(38,0),
	SOURCE_TYPE VARCHAR(16777216)
);