CREATE OR REPLACE TABLE SERVE.SKILL_JOB_COUNTS (
    SKILL_NAME STRING NOT NULL,
    ACTIVE_JOB_COUNT INTEGER NOT NULL,
    LAST_UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SKILL_NAME)
)
COMMENT = 'Simple lookup table for UI to show number of active jobs per skill'
;