CREATE TABLE IF NOT EXISTS SERVE.DENORM_JOB_POSTINGS (
    -- Primary Identifiers
    JOB_UID STRING PRIMARY KEY,              -- Natural key from STAGE.JOBS_UNIFIED
    JOB_ID STRING,
    PLATFORM STRING,
    COMPANY_ID STRING,
    COMPANY_NAME STRING,

    -- Job Details
    JOB_TITLE STRING,
    JOB_DESCRIPTION STRING,
    JOB_URL STRING,
    DATE_POSTED DATE,
    DATE_RETRIEVED DATE,
    IS_ACTIVE BOOLEAN,
    DATA_QUALITY_SCORE FLOAT,
    TRANSFORMATION_TIMESTAMP TIMESTAMP_NTZ,

    -- Enriched Salary Information
    ENRICHED_SALARY_MIN NUMBER(18,2),
    ENRICHED_SALARY_MAX NUMBER(18,2),
    ENRICHED_SALARY_CURRENCY STRING,
    ENRICHED_SALARY_PERIOD STRING,           -- e.g., year, hour
    ENRICHED_SALARY_TYPE STRING,            -- base, total, etc.

    -- Enriched Experience Information
    ENRICHED_MIN_YEARS_EXPERIENCE NUMBER(5,2),
    ENRICHED_MAX_YEARS_EXPERIENCE NUMBER(5,2),
    ENRICHED_EXPERIENCE_LEVEL STRING,

    -- Enriched Skills & Keywords (comma-separated lists for quick search)
    TECHNICAL_SKILLS_CSV STRING,       -- Aggregated technical skills list
    SOFT_SKILLS_CSV STRING,            -- Aggregated soft skills list
    ENRICHED_PRIMARY_KEYWORDS STRING,
    ENRICHED_INDUSTRY_KEYWORDS STRING,

    -- Other Enriched Attributes
    ENRICHED_WORK_TYPE STRING,
    ENRICHED_OFFICE_LOCATIONS STRING,
    ENRICHED_ROLE_TYPE STRING,
    ENRICHED_TEAM_SIZE STRING,

    -- Confidence Scores
    ENRICHED_OVERALL_CONFIDENCE FLOAT,
    ENRICHED_SALARY_CONFIDENCE FLOAT,
    ENRICHED_EXPERIENCE_CONFIDENCE FLOAT,
    ENRICHED_SKILLS_CONFIDENCE FLOAT,
    ENRICHED_WORK_ARRANGEMENT_CONFIDENCE FLOAT,
    ENRICHED_CLASSIFICATION_CONFIDENCE FLOAT,

    -- Aggregated Lists for Search Optimisation
    SKILLS_CSV STRING,          -- All skills list
    KEYWORDS_CSV STRING,        -- Pre-flattened keywords list (lowercase, comma-separated)

    -- Audit Fields
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,

    -- Partitioning / Clustering
    PARTITION_DATE DATE          -- Typically POSTING_DATE truncated to month for clustering
) CLUSTER BY (PARTITION_DATE, PLATFORM);