CREATE TABLE IF NOT EXISTS SERVE.DENORM_KEYWORDS (
    KEYWORD STRING NOT NULL,
    KEYWORD_TYPE STRING NOT NULL,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (KEYWORD)
) COMMENT = 'Flat keyword lookup table for UI autocomplete/search, generated from DIM_KEYWORDS.';