create if not exists TABLE BETTERJOBS_DB.STAGE.KEYWORDS_NORMALIZED cluster by (KEYWORD_TYPE, KEYWORD_TEXT)(
	KEYWORD_ID VARCHAR(16777216) NOT NULL,
	KEYWORD_TEXT VARCHAR(16777216) NOT NULL,
	KEYWORD_TEXT_CLEAN VARCHAR(16777216) NOT NULL,
	KEYWORD_TYPE VARCHAR(16777216) NOT NULL,
	KEYWORD_CATEGORY VARCHAR(16777216),
	ORIGINAL_VARIANTS VARIANT,
	CANONICAL_FORM VARCHAR(16777216),
	FREQUENCY_COUNT NUMBER(38,0) DEFAULT 0,
	TREND_SCORE FLOAT DEFAULT 0,
	CONFIDENCE_SCORE FLOAT DEFAULT 1,
	APPROVED_BY_ADMIN BOOLEAN DEFAULT FALSE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (KEYWORD_ID)
);