CREATE TABLE IF NOT EXISTS BETTERJOBS_DB.STAGE.JOB_SKILLS_BRIDGE cluster by (JOB_UID, SKILL_CATEGORY)(
	BRIDGE_ID VARCHAR(16777216) NOT NULL,
	JOB_UID VARCHAR(16777216) NOT NULL,
	SKILL_ID VARCHAR(16777216) NOT NULL,
	SKILL_SOURCE VARCHAR(16777216) NOT NULL,
	SKILL_CATEGORY VARCHAR(16777216) NOT NULL,
	ORIGINAL_TEXT VARCHAR(16777216),
	EXTRACTION_CONFIDENCE FLOAT,
	STANDARDIZATION_CONFIDENCE FLOAT,
	OVERALL_CONFIDENCE FLOAT,
	SKILL_CONTEXT VARCHAR(16777216),
	PROCESSING_METHOD VARCHAR(16777216) DEFAULT 'llm_auto',
	NEEDS_REVIEW BOOLEAN DEFAULT FALSE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(16777216) DEFAULT 'system',
	primary key (BRIDGE_ID),
	constraint FK_JOB_SKILLS_JOB_UID foreign key (JOB_UID) references BETTERJOBS_DB.STAGE.JOBS_UNIFIED(JOB_UID),
	constraint FK_JOB_SKILLS_SKILL_ID foreign key (SKILL_ID) references BETTERJOBS_DB.STAGE.SKILLS_NORMALIZED(SKILL_ID)
);