create or replace TABLE BETTERJOBS_DB.STAGE.JOB_LOCATIONS_BRIDGE cluster by (JOB_UID, LOCATION_SOURCE)(
	BRIDGE_ID VARCHAR(16777216) NOT NULL,
	JOB_UID VARCHAR(16777216) NOT NULL,
	LOCATION_ID VARCHAR(16777216) NOT NULL,
	LOCATION_SOURCE VARCHAR(16777216) NOT NULL,
	ORIGINAL_TEXT VARCHAR(16777216),
	LOCATION_CONTEXT VARCHAR(16777216),
	WORK_ARRANGEMENT VARCHAR(16777216),
	EXTRACTION_CONFIDENCE FLOAT,
	STANDARDIZATION_CONFIDENCE FLOAT,
	OVERALL_CONFIDENCE FLOAT,
	PROCESSING_METHOD VARCHAR(16777216) DEFAULT 'llm_auto',
	NEEDS_REVIEW BOOLEAN DEFAULT FALSE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(16777216) DEFAULT 'system',
	primary key (BRIDGE_ID),
	constraint FK_JOB_LOCATIONS_JOB_UID foreign key (JOB_UID) references BETTERJOBS_DB.STAGE.JOBS_UNIFIED(JOB_UID),
	constraint FK_JOB_LOCATIONS_LOCATION_ID foreign key (LOCATION_ID) references BETTERJOBS_DB.STAGE.LOCATIONS_NORMALIZED(LOCATION_ID)
);