create or replace TABLE BETTERJOBS_DB.STAGE.KEYWORD_TYPE_MAPPING cluster by (KEYWORD_TYPE, IS_ACTIVE)(
	MAPPING_ID VARCHAR(16777216) NOT NULL,
	KEYWORD_TEXT VARCHAR(16777216) NOT NULL,
	KEYWORD_TYPE VARCHAR(16777216) NOT NULL,
	KEYWORD_CATEGORY VARCHAR(16777216) NOT NULL,
	CATEGORY_DESCRIPTION VARCHAR(16777216),
	CONFIDENCE_SCORE FLOAT DEFAULT 1,
	BUSINESS_RELEVANCE VARCHAR(16777216) DEFAULT 'medium',
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (MAPPING_ID)
);