CREATE TABLE IF NOT EXISTS BETTERJOBS_DB.STAGE.JOB_SALARY_BRIDGE CLUSTER BY (JOB_UID) (
    BRIDGE_ID VARCHAR(16777216) NOT NULL,
    JOB_UID VARCHAR(16777216) NOT NULL,
    SALARY_ID VARCHAR(16777216) NOT NULL,

    -- Bridge-specific metadata
    OVERALL_CONFIDENCE FLOAT,
    SALARY_SOURCE VARCHAR(16777216),
    EXTRACTION_METHOD VARCHAR(16777216),

    -- Quality flags
    NEEDS_REVIEW BOOLEAN DEFAULT FALSE,
    VALIDATION_STATUS VARCHAR(16777216) DEFAULT 'pending',

    CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (BRIDGE_ID),
    CONSTRAINT FK_JOB_SALARY_JOB_UID FOREIGN KEY (JOB_UID) REFERENCES BETTERJOBS_DB.STAGE.JOBS_UNIFIED(JOB_UID),
    CONSTRAINT FK_JOB_SALARY_SALARY_ID FOREIGN KEY (SALARY_ID) REFERENCES BETTERJOBS_DB.STAGE.SALARY_NORMALIZED(SALARY_ID)
);