create or replace TABLE BETTERJOBS_DB.STAGE.LLM_QUALITY_METRICS_HISTORY cluster by (METRIC_ID, CALCULATION_TIMESTAMP)(
	HISTORY_ID VARCHAR(16777216) NOT NULL,
	METRIC_ID VARCHAR(16777216) NOT NULL,
	METRIC_VALUE FLOAT NOT NULL,
	CALCULATION_TIMESTAMP TIMESTAMP_NTZ(9) NOT NULL,
	CHANGE_FROM_PREVIOUS FLOAT,
	TREND_DIRECTION VARCHAR(16777216),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (HISTORY_ID)
);