create or replace TABLE BETTERJOBS_DB.STAGE.SKILL_FAMILY_MAPPING cluster by (SKILL_CATEGORY, IS_ACTIVE)(
	MAPPING_ID VARCHAR(16777216) NOT NULL,
	SKILL_CATEGORY VARCHAR(16777216) NOT NULL,
	SKILL_FAMILY VARCHAR(16777216) NOT NULL,
	FAMILY_DESCRIPTION VARCHAR(16777216),
	PRIORITY NUMBER(38,0) DEFAULT 1,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (MAPPING_ID)
);