CREATE TABLE IF NOT EXISTS BETTERJOBS_DB.STAGE.KEYWORD_STANDARDIZATION_RULES cluster by (KEYWORD_TYPE, IS_ACTIVE)(
	RULE_ID VARCHAR(16777216) NOT NULL,
	PATTERN VARCHAR(16777216) NOT NULL,
	STANDARDIZED_TEXT VARCHAR(16777216) NOT NULL,
	KEYWORD_TYPE VARCHAR(16777216) NOT NULL,
	KEYWORD_CATEGORY VARCHAR(16777216),
	CONFIDENCE_SCORE FLOAT DEFAULT 1,
	RULE_TYPE VARCHAR(16777216) DEFAULT 'exact_match',
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (RULE_ID)
);