create if not exists TABLE BETTERJOBS_DB.STAGE.US_STATES_MAPPING cluster by (STATE_ABBREVIATION, STATE_NAME_FULL)(
	STATE_ID VARCHAR(16777216) NOT NULL,
	STATE_NAME_FULL VARCHAR(16777216) NOT NULL,
	STATE_ABBREVIATION VARCHAR(16777216) NOT NULL,
	COUNTRY VARCHAR(16777216) DEFAULT 'United States',
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (STATE_ID)
);