CREATE TABLE IF NOT EXISTS BETTERJOBS_DB.STAGE.SKILL_1_SUBCATEGORY (
        ID INTEGER PRIMARY KEY,
        NAME STRING NOT NULL,
        LEVEL INTEGER DEFAULT 1,
        CATEGORY INTEGER,
        CATEGORY_NAME STRING,
        DESCRIPTION TEXT,
        VERSION STRING DEFAULT '9.31',
        LATEST_VERSION BOOLEAN DEFAULT TRUE,
        CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
        UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (CATEGORY) REFERENCES BETTERJOBS_DB.STAGE.SKILL_0_CATEGORY(ID)
    ) CLUSTER BY (CATEGORY, ID);