CREATE TABLE IF NOT EXISTS BETTERJOBS_DB.STAGE.JOB_KEYWORDS_BRIDGE cluster by (JOB_UID, KEYWORD_SOURCE)(
	BRIDGE_ID VARCHAR(16777216) NOT NULL,
	JOB_UID VARCHAR(16777216) NOT NULL,
	KEYWORD_ID VARCHAR(16777216) NOT NULL,
	KEYWORD_SOURCE VARCHAR(16777216) NOT NULL,
	ORIGINAL_TEXT VARCHAR(16777216),
	EXTRACTION_CONFIDENCE FLOAT,
	STANDARDIZATION_CONFIDENCE FLOAT,
	OVERALL_CONFIDENCE FLOAT,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (BRIDGE_ID),
	constraint FK_JOB_KEYWORDS_JOB_UID foreign key (JOB_UID) references BETTERJOBS_DB.STAGE.JOBS_UNIFIED(JOB_UID),
	constraint FK_JOB_KEYWORDS_KEYWORD_ID foreign key (KEYWORD_ID) references BETTERJOBS_DB.STAGE.KEYWORDS_NORMALIZED(KEYWORD_ID)
);