create if not exists TABLE BETTERJOBS_DB.STAGE.LLM_CONFIDENCE_MONITORING cluster by (DATA_SOURCE, CONFIDENCE_BUCKET)(
	MONITORING_ID VARCHAR(16777216) NOT NULL,
	DATA_SOURCE VARCHAR(16777216) NOT NULL,
	CONFIDENCE_BUCKET VARCHAR(16777216) NOT NULL,
	ITEM_COUNT NUMBER(38,0) NOT NULL,
	PERCENTAGE_OF_TOTAL FLOAT NOT NULL,
	AVG_CONFIDENCE_IN_BUCKET FLOAT NOT NULL,
	TREND_DIRECTION VARCHAR(16777216),
	QUALITY_RATING VARCHAR(16777216) NOT NULL,
	ACTION_REQUIRED VARCHAR(16777216) NOT NULL,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(16777216) DEFAULT 'system',
	primary key (MONITORING_ID)
);