CREATE TABLE IF NOT EXISTS BETTERJOBS_DB.STAGE.JOB_EXPERIENCE_BRIDGE (
    BRIDGE_ID STRING PRIMARY KEY,
    JOB_UID STRING NOT NULL,
    EXPERIENCE_ID STRING NOT NULL,
    EXPERIENCE_SOURCE STRING NOT NULL,       -- 'llm_min_years', 'llm_max_years', 'llm_level', 'llm_seniority'
    EXPERIENCE_VALUE_NUMERIC INTEGER,        -- Years required (for numeric requirements)
    EXPERIENCE_VALUE_TEXT STRING,            -- Level name (for categorical requirements)
    TECHNOLOGY_CONTEXT STRING,               -- Technology name if tech-specific (e.g., 'Python: 3 years')
    IS_MINIMUM_REQUIREMENT BOOLEAN DEFAULT TRUE,  -- true=minimum, false=preferred
    EXTRACTION_CONFIDENCE FLOAT,             -- Confidence from LLM extraction
    PROCESSING_METHOD STRING DEFAULT 'llm_auto',
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (JOB_UID) REFERENCES BETTERJOBS_DB.STAGE.JOBS_UNIFIED(JOB_UID),
    FOREIGN KEY (EXPERIENCE_ID) REFERENCES BETTERJOBS_DB.STAGE.EXPERIENCE_NORMALIZED(EXPERIENCE_ID)
) CLUSTER BY (JOB_UID, EXPERIENCE_SOURCE);