CREATE TABLE IF NOT EXISTS BETTERJOBS_DB.STAGE.MANUAL_SKILL_TAXONOMY (
    SKILL_NAME STRING PRIMARY KEY,
    LIGHTCAST_CATEGORY_NAME STRING,
    LIGHTCAST_SUBCATEGORY_NAME STRING,
    MATCH_CONFIDENCE FLOAT,
    SOURCE STRING DEFAULT 'gemini_auto',
    VERSION STRING DEFAULT 'v1',
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);