create or replace TABLE BETTERJOBS_DB.STAGE.SKILL_CATEGORY_PATTERNS cluster by (SKILL_CATEGORY, IS_ACTIVE)(
	PATTERN_ID VARCHAR(16777216) NOT NULL,
	SKILL_CATEGORY VARCHAR(16777216) NOT NULL,
	PATTERN VARCHAR(16777216) NOT NULL,
	PATTERN_TYPE VARCHAR(16777216) DEFAULT 'regex',
	CONFIDENCE_SCORE FLOAT DEFAULT 1,
	DESCRIPTION VARCHAR(16777216),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (PATTERN_ID)
);