CREATE TABLE IF NOT EXISTS BETTERJOBS_DB.STAGE.LOCATION_REGION_MAPPING cluster by (COUNTRY, REGION)(
	MAPPING_ID VARCHAR(16777216) NOT NULL,
	STATE_PROVINCE VARCHAR(16777216) NOT NULL,
	COUNTRY VARCHAR(16777216) NOT NULL,
	REGION VARCHAR(16777216) NOT NULL,
	REGION_DESCRIPTION VARCHAR(16777216),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (MAPPING_ID)
);