CREATE TABLE IF NOT EXISTS BETTERJOBS_DB.STAGE.LOCATION_METRO_AREA_MAPPING cluster by (COUNTRY, STATE_PROVINCE)(
	MAPPING_ID VARCHAR(16777216) NOT NULL,
	CITY VARCHAR(16777216) NOT NULL,
	STATE_PROVINCE VARCHAR(16777216) NOT NULL,
	COUNTRY VARCHAR(16777216) NOT NULL,
	METRO_AREA VARCHAR(16777216) NOT NULL,
	IS_PRIMARY_CITY BOOLEAN DEFAULT FALSE,
	CONFIDENCE_SCORE FLOAT DEFAULT 1,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (MAPPING_ID)
);