create if not exists TABLE BETTERJOBS_DB.STAGE.LOCATION_TECH_HUB_MAPPING cluster by (COUNTRY, STATE_PROVINCE)(
	MAPPING_ID VARCHAR(16777216) NOT NULL,
	CITY VARCHAR(16777216) NOT NULL,
	STATE_PROVINCE VARCHAR(16777216) NOT NULL,
	COUNTRY VARCHAR(16777216) NOT NULL,
	IS_MAJOR_TECH_HUB BOOLEAN DEFAULT TRUE,
	TECH_HUB_TYPE VARCHAR(16777216),
	HUB_DESCRIPTION VARCHAR(16777216),
	CONFIDENCE_SCORE FLOAT DEFAULT 1,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (MAPPING_ID)
);