CREATE TABLE IF NOT EXISTS BETTERJOBS_DB.STAGE.VIEW_VERSION_TRACKING (
    VIEW_NAME STRING PRIMARY KEY,
    CONTENT_HASH STRING NOT NULL,
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    FILE_PATH STRING,
    VIEW_SCHEMA STRING,
    UPDATED_BY STRING DEFAULT 'dagster_pipeline',
    PREVIOUS_HASH STRING,
    UPDATE_REASON STRING DEFAULT 'content_changed',
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
) CLUSTER BY (VIEW_SCHEMA, VIEW_NAME);