CREATE TABLE IF NOT EXISTS BETTERJOBS_DB.STAGE.LLM_COVERAGE_ANALYSIS cluster by (ANALYSIS_TYPE, DIMENSION_NAME)(
	ANALYSIS_ID VARCHAR(16777216) NOT NULL,
	ANALYSIS_TYPE VARCHAR(16777216) NOT NULL,
	DIMENSION_NAME VARCHAR(16777216) NOT NULL,
	DIMENSION_VALUE VARCHAR(16777216) NOT NULL,
	TOTAL_JOBS NUMBER(38,0) NOT NULL,
	JOBS_WITH_SKILLS NUMBER(38,0) NOT NULL,
	JOBS_WITH_KEYWORDS NUMBER(38,0) NOT NULL,
	JOBS_WITH_LOCATIONS NUMBER(38,0) NOT NULL,
	SKILLS_COVERAGE_PCT FLOAT NOT NULL,
	KEYWORDS_COVERAGE_PCT FLOAT NOT NULL,
	LOCATIONS_COVERAGE_PCT FLOAT NOT NULL,
	GAP_ANALYSIS VARCHAR(16777216),
	RECOMMENDATIONS VARCHAR(16777216),
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(16777216) DEFAULT 'system',
	primary key (ANALYSIS_ID)
);