CREATE TABLE IF NOT EXISTS BETTERJOBS_DB.STAGE.SKILLS_CONSOLIDATED CLUSTER BY (SKILL_CATEGORY, CANONICAL_SKILL_NAME)(
	CONSOLIDATED_SKILL_ID VARCHAR(16777216) NOT NULL,
	CANONICAL_SKILL_NAME VARCHAR(16777216) NOT NULL,
	SKILL_CATEGORY VARCHAR(16777216) NOT NULL,
	SKILL_SUBCATEGORY VARCHAR(16777216),
	SKILL_FAMILY VARCHAR(16777216),
	SKILL_TYPE VARCHAR(16777216) DEFAULT 'technical',

	-- Consolidation metadata
	ORIGINAL_SKILL_IDS VARIANT,          -- Array of original skill IDs that were merged
	ORIGINAL_SKILL_NAMES VARIANT,        -- Array of original skill names
	CONSOLIDATION_METHOD VARCHAR(16777216), -- 'none', 'singular_plural', 'abbreviation', etc.

	-- Aggregated data
	TOTAL_FREQUENCY_COUNT NUMBER(38,0) DEFAULT 0,
	CONSOLIDATED_CONFIDENCE_SCORE FLOAT DEFAULT 1.0,
	FIRST_SEEN_DATE DATE,
	LAST_SEEN_DATE DATE,

	-- Trend and quality tracking
	TREND_DIRECTION VARCHAR(16777216),
	MANUAL_REVIEW_FLAG BOOLEAN DEFAULT FALSE,
	APPROVED_BY_ADMIN BOOLEAN DEFAULT FALSE,

	-- Audit trail
	CONSOLIDATION_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CONSOLIDATION_VERSION VARCHAR(16777216) DEFAULT '1.0',
	CREATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(16777216) DEFAULT 'system',

	primary key (CONSOLIDATED_SKILL_ID)
);