CREATE VIEW ANALYTICS.SKILLS_MARKET_INTELLIGENCE AS
WITH SKILL_DEMAND_TRENDS AS (
    SELECT
        S.SKILL_NAME,
        S.SKILL_CATEGORY,
        S.SKILL_SUBCATEGORY,
        DATE_TRUNC('week', F.FIRST_POSTED_DATE) AS DEMAND_WEEK,
        COUNT(DISTINCT F.JOB_POSTING_KEY) AS JOBS_REQUIRING_SKILL,

        -- Market Penetration Calculation
        COUNT(DISTINCT F.JOB_POSTING_KEY)::FLOAT /
        SUM(COUNT(DISTINCT F.JOB_POSTING_KEY)) OVER (PARTITION BY DATE_TRUNC('week', F.FIRST_POSTED_DATE)) * 100 AS MARKET_PENETRATION_RATE,

        -- Salary Analysis (ENHANCEMENT-022: Using normalized annual USD)
        AVG(F.SALARY_MIDPOINT_ANNUAL_USD) AS AVG_SALARY_WITH_SKILL,

        -- Remote Work Analysis
        COUNT(CASE WHEN F.WORK_TYPE = 'Remote' THEN 1 END)::FLOAT / COUNT(*) * 100 AS REMOTE_AVAILABILITY_RATE

    FROM ANALYTICS.FACT_JOB_POSTINGS F
    JOIN STAGE.JOB_SKILLS_BRIDGE JSB ON F.JOB_UID = JSB.JOB_UID
    JOIN ANALYTICS.DIM_SKILLS S ON JSB.SKILL_ID = S.SKILL_ID
    JOIN ANALYTICS.DIM_DATE D ON F.DATE_POSTED_KEY = D.DATE_KEY

    WHERE D.FULL_DATE >= CURRENT_DATE - 90
      AND F.IS_ACTIVE_POSTING = TRUE
      AND F.SALARY_MIDPOINT_ANNUAL_USD IS NOT NULL

    GROUP BY S.SKILL_NAME, S.SKILL_CATEGORY, S.SKILL_SUBCATEGORY, DATE_TRUNC('week', F.FIRST_POSTED_DATE)
    HAVING COUNT(DISTINCT F.JOB_POSTING_KEY) >= 5  -- Minimum threshold for reliability
)

SELECT
    SKILL_NAME,
    SKILL_CATEGORY,
    SKILL_SUBCATEGORY,
    DEMAND_WEEK,
    JOBS_REQUIRING_SKILL,
    MARKET_PENETRATION_RATE,

    -- Growth Analysis
    LAG(JOBS_REQUIRING_SKILL, 1) OVER (PARTITION BY SKILL_NAME ORDER BY DEMAND_WEEK) AS PREV_WEEK_DEMAND,
    ((JOBS_REQUIRING_SKILL::FLOAT / LAG(JOBS_REQUIRING_SKILL, 1) OVER (PARTITION BY SKILL_NAME ORDER BY DEMAND_WEEK)) - 1) * 100 AS WOW_GROWTH_RATE,

    -- Salary Intelligence
    AVG_SALARY_WITH_SKILL,
    REMOTE_AVAILABILITY_RATE,

    -- Market Classification
    CASE
        WHEN MARKET_PENETRATION_RATE > 20 THEN 'POPULAR'
        WHEN MARKET_PENETRATION_RATE > 5 THEN 'NICHE'
        ELSE 'SPECIALIZED'
    END AS MARKET_ADOPTION_LEVEL,

    -- Trend Classification
    CASE
        WHEN ((JOBS_REQUIRING_SKILL::FLOAT / LAG(JOBS_REQUIRING_SKILL, 1) OVER (PARTITION BY SKILL_NAME ORDER BY DEMAND_WEEK)) - 1) * 100 > 25 THEN 'HOT'
        WHEN ((JOBS_REQUIRING_SKILL::FLOAT / LAG(JOBS_REQUIRING_SKILL, 1) OVER (PARTITION BY SKILL_NAME ORDER BY DEMAND_WEEK)) - 1) * 100 > 10 THEN 'GROWING'
        WHEN ((JOBS_REQUIRING_SKILL::FLOAT / LAG(JOBS_REQUIRING_SKILL, 1) OVER (PARTITION BY SKILL_NAME ORDER BY DEMAND_WEEK)) - 1) * 100 > -10 THEN 'STABLE'
        ELSE 'DECLINING'
    END AS TREND_CATEGORY

FROM SKILL_DEMAND_TRENDS
ORDER BY DEMAND_WEEK DESC, JOBS_REQUIRING_SKILL DESC;