CREATE VIEW ANALYTICS.WEEKLY_MARKET_OVERVIEW AS
SELECT
    DATE_TRUNC('week', F.FIRST_POSTED_DATE) AS REPORT_WEEK,

    -- Key Metrics
    COUNT(*) AS TOTAL_JOB_POSTINGS,
    COUNT(DISTINCT F.COMPANY_KEY) AS ACTIVE_COMPANIES,
    COUNT(CASE WHEN F.IS_ACTIVE_POSTING THEN 1 END) AS ACTIVE_POSTINGS,

    -- Salary Intelligence
    AVG(F.SALARY_MIN + F.SALARY_MAX) / 2 AS AVG_SALARY_MIDPOINT,
    MEDIAN((F.SALARY_MIN + F.SALARY_MAX) / 2) AS MEDIAN_SALARY_MIDPOINT,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY (F.SALARY_MIN + F.SALARY_MAX) / 2) AS P75_SALARY,

    -- Remote Work Trends
    COUNT(CASE WHEN F.WORK_TYPE = 'Remote' THEN 1 END)::FLOAT / COUNT(*) * 100 AS REMOTE_PERCENTAGE,
    COUNT(CASE WHEN F.WORK_TYPE = 'Hybrid' THEN 1 END)::FLOAT / COUNT(*) * 100 AS HYBRID_PERCENTAGE,
    COUNT(CASE WHEN F.WORK_TYPE = 'On-site' THEN 1 END)::FLOAT / COUNT(*) * 100 AS ONSITE_PERCENTAGE,

    -- Geographic Distribution
    COUNT(DISTINCT L.LOCATION_KEY) AS UNIQUE_LOCATIONS,

    -- Experience Level Distribution
    COUNT(CASE WHEN F.SENIORITY_LEVEL = 'Entry' THEN 1 END) AS ENTRY_LEVEL_JOBS,
    COUNT(CASE WHEN F.SENIORITY_LEVEL = 'Mid' THEN 1 END) AS MID_LEVEL_JOBS,
    COUNT(CASE WHEN F.SENIORITY_LEVEL = 'Senior' THEN 1 END) AS SENIOR_LEVEL_JOBS,

    -- Growth Metrics
    LAG(COUNT(*)) OVER (ORDER BY DATE_TRUNC('week', F.FIRST_POSTED_DATE)) AS PREV_WEEK_POSTINGS,
    (COUNT(*)::FLOAT / LAG(COUNT(*)) OVER (ORDER BY DATE_TRUNC('week', F.FIRST_POSTED_DATE)) - 1) * 100 AS WOW_GROWTH_RATE,

    -- Quality Metrics
    AVG(F.DATA_QUALITY_SCORE) AS AVG_DATA_QUALITY_SCORE,
    COUNT(CASE WHEN F.SALARY_MIN IS NOT NULL AND F.SALARY_MAX IS NOT NULL THEN 1 END)::FLOAT / COUNT(*) * 100 AS SALARY_DISCLOSURE_RATE

FROM ANALYTICS.FACT_JOB_POSTINGS F
JOIN ANALYTICS.DIM_DATE D ON F.DATE_POSTED_KEY = D.DATE_KEY
JOIN ANALYTICS.DIM_COMPANY C ON F.COMPANY_KEY = C.COMPANY_KEY
JOIN ANALYTICS.DIM_LOCATION L ON F.LOCATION_KEY = L.LOCATION_KEY

WHERE D.FULL_DATE >= CURRENT_DATE - 90
  AND F.IS_ACTIVE_POSTING = TRUE

GROUP BY DATE_TRUNC('week', F.FIRST_POSTED_DATE)
ORDER BY REPORT_WEEK DESC;