CREATE VIEW ANALYTICS.SALARY_INTELLIGENCE AS
SELECT
    JF.JOB_FAMILY,
    JF.SENIORITY_LEVEL,
    L.METRO_AREA,
    L.COUNTRY,
    DATE_TRUNC('month', F.FIRST_POSTED_DATE) AS SALARY_MONTH,

    -- Statistical Measures
    COUNT(*) AS SAMPLE_SIZE,
    AVG((F.SALARY_MIN + F.SALARY_MAX) / 2) AS MEAN_SALARY,
    MEDIAN((F.SALARY_MIN + F.SALARY_MAX) / 2) AS MEDIAN_SALARY,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY (F.SALARY_MIN + F.SALARY_MAX) / 2) AS P25_SALARY,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY (F.SALARY_MIN + F.SALARY_MAX) / 2) AS P75_SALARY,
    PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY (F.SALARY_MIN + F.SALARY_MAX) / 2) AS P90_SALARY,

    -- Growth Metrics
    LAG(AVG((F.SALARY_MIN + F.SALARY_MAX) / 2)) OVER (
        PARTITION BY JF.JOB_FAMILY, JF.SENIORITY_LEVEL, L.METRO_AREA
        ORDER BY DATE_TRUNC('month', F.FIRST_POSTED_DATE)
    ) AS PREV_MONTH_AVG_SALARY,

    ((AVG((F.SALARY_MIN + F.SALARY_MAX) / 2) / LAG(AVG((F.SALARY_MIN + F.SALARY_MAX) / 2)) OVER (
        PARTITION BY JF.JOB_FAMILY, JF.SENIORITY_LEVEL, L.METRO_AREA
        ORDER BY DATE_TRUNC('month', F.FIRST_POSTED_DATE)
    )) - 1) * 100 AS MOM_SALARY_GROWTH,

    -- Work Arrangement Impact
    AVG(CASE WHEN F.WORK_TYPE = 'Remote' THEN (F.SALARY_MIN + F.SALARY_MAX) / 2 END) AS AVG_REMOTE_SALARY,
    AVG(CASE WHEN F.WORK_TYPE = 'On-site' THEN (F.SALARY_MIN + F.SALARY_MAX) / 2 END) AS AVG_ONSITE_SALARY,

    -- Quality Indicators
    AVG(F.SALARY_CONFIDENCE) AS AVG_CONFIDENCE_SCORE,
    COUNT(CASE WHEN F.SALARY_MIN IS NOT NULL AND F.SALARY_MAX IS NOT NULL THEN 1 END)::FLOAT / COUNT(*) * 100 AS DISCLOSURE_RATE

FROM ANALYTICS.FACT_JOB_POSTINGS F
JOIN ANALYTICS.DIM_JOB_FAMILY JF ON F.JOB_FAMILY_KEY = JF.JOB_FAMILY_KEY
JOIN ANALYTICS.DIM_LOCATION L ON F.LOCATION_KEY = L.LOCATION_KEY
JOIN ANALYTICS.DIM_DATE D ON F.DATE_POSTED_KEY = D.DATE_KEY

WHERE F.SALARY_MIN IS NOT NULL
  AND F.SALARY_MAX IS NOT NULL
  AND (F.SALARY_MIN + F.SALARY_MAX) / 2 BETWEEN 30000 AND 500000  -- Reasonable bounds
  AND F.IS_ACTIVE_POSTING = TRUE
  AND D.FULL_DATE >= CURRENT_DATE - 365

GROUP BY JF.JOB_FAMILY, JF.SENIORITY_LEVEL, L.METRO_AREA, L.COUNTRY, DATE_TRUNC('month', F.FIRST_POSTED_DATE)
HAVING COUNT(*) >= 5  -- Minimum sample size for statistical validity
ORDER BY JF.JOB_FAMILY, JF.SENIORITY_LEVEL, L.METRO_AREA, SALARY_MONTH DESC;