CREATE VIEW IF NOT EXISTS BETTERJOBS_DB.INTERNAL.2_REVIEW_SKILLS_QUEUE(
    JOB_UID,
    JOB_TITLE_CLEAN,
    JOB_URL,
    SKILL_ID,
    SKILL_NAME,
    SKILL_CATEGORY,
    SKILL_CONFIDENCE,
    OVERALL_CONFIDENCE,
    NEEDS_REVIEW_REASON
) AS
SELECT
    JU.JOB_UID,
    JU.JOB_TITLE_CLEAN,
    JU.JOB_URL,
    SN.SKILL_ID,
    SN.SKILL_NAME,
    SN.SKILL_CATEGORY,
    SN.CONFIDENCE_SCORE as SKILL_CONFIDENCE,
    JSB.OVERALL_CONFIDENCE,
    CASE
        WHEN SN.CONFIDENCE_SCORE < 0.5 THEN 'Low skill confidence'
        WHEN JSB.OVERALL_CONFIDENCE < 0.5 THEN 'Low relationship confidence'
        WHEN SN.MANUAL_REVIEW_FLAG THEN 'Manual review flagged'
        ELSE 'Other'
    END as NEEDS_REVIEW_REASON
FROM BETTERJOBS_DB.STAGE.JOB_SKILLS_BRIDGE JSB
INNER JOIN BETTERJOBS_DB.STAGE.SKILLS_NORMALIZED SN
    ON SN.SKILL_ID = JSB.SKILL_ID
INNER JOIN BETTERJOBS_DB.STAGE.JOBS_UNIFIED JU
    ON JU.JOB_UID = JSB.JOB_UID
WHERE JSB.NEEDS_REVIEW = TRUE
   OR SN.CONFIDENCE_SCORE < 0.5
   OR SN.MANUAL_REVIEW_FLAG = TRUE;