create if not exists view BETTERJOBS_DB.STAGE.SKILLS_ANALYSIS(
	SKILL_NAME,
	SKILL_CATEGORY,
	SKILL_SUBCATEGORY,
	FREQUENCY,
	PLATFORMS,
	AVG_CONFIDENCE,
	TREND_DIRECTION,
	TOTAL_MARKET_FREQUENCY
) as
SELECT
    sn.SKILL_NAME,
    sn.SKILL_CATEGORY,
    sn.SKILL_SUBCATEGORY,
    COUNT(DISTINCT jsb.JOB_UID) as FREQUENCY,
    ARRAY_AGG(DISTINCT j.PLATFORM) as PLATFORMS,
    AVG(jsb.OVERALL_CONFIDENCE) as AVG_CONFIDENCE,
    sn.TREND_DIRECTION,
    sn.FREQUENCY_COUNT as TOTAL_MARKET_FREQUENCY
FROM SKILLS_NORMALIZED sn
LEFT JOIN JOB_SKILLS_BRIDGE jsb ON sn.SKILL_ID = jsb.SKILL_ID
LEFT JOIN JOBS_UNIFIED j ON jsb.JOB_UID = j.JOB_UID
WHERE j.IS_ENGLISH = TRUE OR j.IS_ENGLISH IS NULL
GROUP BY sn.SKILL_NAME, sn.SKILL_CATEGORY, sn.SKILL_SUBCATEGORY, sn.TREND_DIRECTION, sn.FREQUENCY_COUNT
ORDER BY FREQUENCY DESC;