CREATE VIEW IF NOT EXISTS BETTERJOBS_DB.STAGE.JOB_SKILLS_COVERAGE(
	TOTAL_JOBS,
	JOBS_WITH_SKILLS,
	COVERAGE_PERCENTAGE,
	AVG_SKILLS_PER_JOB
) as
SELECT
    COUNT(DISTINCT ju.JOB_UID) as TOTAL_JOBS,
    COUNT(DISTINCT jsb.JOB_UID) as JOBS_WITH_SKILLS,
    ROUND((COUNT(DISTINCT jsb.JOB_UID)::FLOAT / COUNT(DISTINCT ju.JOB_UID)) * 100, 2) as COVERAGE_PERCENTAGE,
    AVG(skills_per_job.SKILL_COUNT) as AVG_SKILLS_PER_JOB
FROM JOBS_UNIFIED ju
LEFT JOIN JOB_SKILLS_BRIDGE jsb ON ju.JOB_UID = jsb.JOB_UID
LEFT JOIN (
    SELECT JOB_UID, COUNT(*) as SKILL_COUNT
    FROM JOB_SKILLS_BRIDGE
    GROUP BY JOB_UID
) skills_per_job ON ju.JOB_UID = skills_per_job.JOB_UID;