CREATE VIEW IF NOT EXISTS BETTERJOBS_DB.STAGE.SKILLS_RAW_EXTRACTION(
	JOB_UID,
	SKILL_SOURCE,
	SKILL_NAME_RAW,
	SKILL_NAME_ORIGINAL,
	LIGHTCAST_SKILL_ID,
	LIGHTCAST_SKILL_NAME,
	LIGHTCAST_SUBCATEGORY_ID,
	LIGHTCAST_SUBCATEGORY_NAME,
	LIGHTCAST_CATEGORY_ID,
	LIGHTCAST_CATEGORY_NAME,
	LIGHTCAST_MATCH_CONFIDENCE
) as
WITH TECHNICAL_SKILLS_EXPLODED AS (
	-- Extract technical skills (now a flat array)
	SELECT
		jle.JOB_UID,
		'technical_skills' as SKILL_SOURCE,
		TRIM(LOWER(SKILL.VALUE::STRING)) as SKILL_NAME_RAW,
		SKILL.VALUE::STRING as SKILL_NAME_ORIGINAL
	FROM BETTERJOBS_DB.STAGE.JOBS_LLM_ENRICHED jle,
	LATERAL FLATTEN(input => jle.TECHNICAL_SKILLS) SKILL
	WHERE jle.TECHNICAL_SKILLS IS NOT NULL
	  AND SKILL.VALUE IS NOT NULL
	  AND LENGTH(TRIM(SKILL.VALUE::STRING)) > 1
	  AND LOWER(TRIM(SKILL.VALUE::STRING)) NOT IN ('null', 'none', 'n/a', '')
),

SOFT_SKILLS_EXPLODED AS (
	-- Extract soft skills (unchanged)
	SELECT
		jle.JOB_UID,
		'soft_skills' as SKILL_SOURCE,
		TRIM(LOWER(SKILL.VALUE::STRING)) as SKILL_NAME_RAW,
		SKILL.VALUE::STRING as SKILL_NAME_ORIGINAL
	FROM BETTERJOBS_DB.STAGE.JOBS_LLM_ENRICHED jle,
	LATERAL FLATTEN(input => jle.SOFT_SKILLS) SKILL
	WHERE jle.SOFT_SKILLS IS NOT NULL
	  AND SKILL.VALUE IS NOT NULL
	  AND LENGTH(TRIM(SKILL.VALUE::STRING)) > 1
	  AND LOWER(TRIM(SKILL.VALUE::STRING)) NOT IN ('null', 'none', 'n/a', '')
),

SKILLS_COMBINED AS (
	SELECT * FROM TECHNICAL_SKILLS_EXPLODED
	UNION ALL
	SELECT * FROM SOFT_SKILLS_EXPLODED
),

LIGHTCAST_MAPPED AS (
	-- Map extracted skills to Lightcast taxonomy
	SELECT
		s.*,
		ls.ID as LIGHTCAST_SKILL_ID,
		ls.NAME as LIGHTCAST_SKILL_NAME,
		ls.SUBCATEGORY as LIGHTCAST_SUBCATEGORY_ID,
		ls.SUBCATEGORY_NAME as LIGHTCAST_SUBCATEGORY_NAME,
		ls.CATEGORY as LIGHTCAST_CATEGORY_ID,
		ls.CATEGORY_NAME as LIGHTCAST_CATEGORY_NAME,
		-- Confidence based on match type
		CASE
			WHEN LOWER(s.SKILL_NAME_RAW) = LOWER(ls.NAME) THEN 1.0
			--WHEN LOWER(s.SKILL_NAME_RAW) LIKE '%' || LOWER(ls.NAME) || '%' THEN 0.9
			ELSE 0.5
		END as LIGHTCAST_MATCH_CONFIDENCE
	FROM SKILLS_COMBINED s
	LEFT JOIN BETTERJOBS_DB.STAGE.SKILL_2_SKILL ls
		ON LOWER(s.SKILL_NAME_RAW) = LOWER(ls.NAME)
		--OR s.SKILL_NAME_RAW ILIKE '%' || ls.NAME || '%'
	WHERE ls.LATEST_VERSION = TRUE OR ls.ID IS NULL
)

SELECT * FROM LIGHTCAST_MAPPED;