create if not exists view BETTERJOBS_DB.STAGE.US_STATES_LOOKUP(
	STATE_NAME,
	COUNTRY
) as
SELECT STATE_NAME_FULL as STATE_NAME, COUNTRY FROM BETTERJOBS_DB.STAGE.US_STATES_MAPPING
UNION ALL
SELECT STATE_ABBREVIATION as STATE_NAME, COUNTRY FROM BETTERJOBS_DB.STAGE.US_STATES_MAPPING;