CREATE VIEW IF NOT EXISTS BETTERJOBS_DB.STAGE.Z_REVIEW_DASHBOARD(
    REVIEW_CATEGORY,
    ITEMS_PENDING,
    AVG_CONFIDENCE,
    OLDEST_ITEM_DAYS,
    PRIORITY_LEVEL
) AS
WITH review_summary AS (
    SELECT
        'Salary' as REVIEW_CATEGORY,
        COUNT(*) as ITEMS_PENDING,
        AVG(SALARY_CONFIDENCE) as AVG_CONFIDENCE,
        MAX(DATEDIFF(day, JU.DATE_RETRIEVED, CURRENT_DATE)) as OLDEST_ITEM_DAYS
    FROM BETTERJOBS_DB.STAGE.Z_REVIEW_SALARY_QUEUE srq
    JOIN BETTERJOBS_DB.STAGE.JOBS_UNIFIED JU ON srq.JOB_UID = JU.JOB_UID

    UNION ALL

    SELECT
        'Skills' as REVIEW_CATEGORY,
        COUNT(*) as ITEMS_PENDING,
        AVG(OVERALL_CONFIDENCE) as AVG_CONFIDENCE,
        MAX(DATEDIFF(day, JU.DATE_RETRIEVED, CURRENT_DATE)) as OLDEST_ITEM_DAYS
    FROM BETTERJOBS_DB.STAGE.Z_REVIEW_SKILLS_QUEUE srq
    JOIN BETTERJOBS_DB.STAGE.JOBS_UNIFIED JU ON srq.JOB_UID = JU.JOB_UID

    UNION ALL

    SELECT
        'Manual Review Queue' as REVIEW_CATEGORY,
        COUNT(*) as ITEMS_PENDING,
        AVG(CONFIDENCE_SCORE) as AVG_CONFIDENCE,
        MAX(DATEDIFF(day, CREATED_TIMESTAMP, CURRENT_DATE)) as OLDEST_ITEM_DAYS
    FROM BETTERJOBS_DB.STAGE.LLM_MANUAL_REVIEW_QUEUE
    WHERE REVIEW_STATUS = 'PENDING'
)
SELECT
    REVIEW_CATEGORY,
    ITEMS_PENDING,
    ROUND(AVG_CONFIDENCE, 3) as AVG_CONFIDENCE,
    OLDEST_ITEM_DAYS,
    CASE
        WHEN ITEMS_PENDING > 1000 OR OLDEST_ITEM_DAYS > 7 THEN '🔴 HIGH'
        WHEN ITEMS_PENDING > 500 OR OLDEST_ITEM_DAYS > 3 THEN '🟡 MEDIUM'
        ELSE '🟢 LOW'
    END as PRIORITY_LEVEL
FROM review_summary
ORDER BY ITEMS_PENDING DESC;