CREATE VIEW IF NOT EXISTS BETTERJOBS_DB.STAGE.LOCATION_PARSING_LOOKUP(
	LOCATION_NAME,
	LOCATION_TYPE,
	COUNTRY,
	REGION,
	IS_MAJOR_TECH_HUB
) as
-- US States (for state detection)
SELECT
    STATE_NAME as LOCATION_NAME,
    'US_STATE' as LOCATION_TYPE,
    'United States' as COUNTRY,
    NULL as REGION,
    FALSE as IS_MAJOR_TECH_HUB
FROM BETTERJOBS_DB.STAGE.US_STATES_LOOKUP
UNION ALL
-- Countries (for country detection)
SELECT
    COUNTRY_NAME as LOCATION_NAME,
    'COUNTRY' as LOCATION_TYPE,
    COUNTRY_NAME as COUNTRY,
    REGION,
    IS_MAJOR_TECH_HUB
FROM BETTERJOBS_DB.STAGE.COUNTRIES_LOOKUP;