create if not exists view BETTERJOBS_DB.STAGE.TOP_LOCATIONS_BY_TYPE(
	LOCATION_TYPE,
	LOCATION_NAME,
	CITY,
	STATE_PROVINCE,
	COUNTRY,
	FREQUENCY_COUNT,
	IS_MAJOR_TECH_HUB,
	CONFIDENCE_SCORE,
	RANK_IN_TYPE
) as
SELECT
    LOCATION_TYPE,
    LOCATION_NAME,
    CITY,
    STATE_PROVINCE,
    COUNTRY,
    FREQUENCY_COUNT,
    IS_MAJOR_TECH_HUB,
    CONFIDENCE_SCORE,
    ROW_NUMBER() OVER (PARTITION BY LOCATION_TYPE ORDER BY FREQUENCY_COUNT DESC) as RANK_IN_TYPE
FROM LOCATIONS_NORMALIZED
WHERE CONFIDENCE_SCORE >= 0.8
ORDER BY LOCATION_TYPE, RANK_IN_TYPE;