CREATE VIEW IF NOT EXISTS BETTERJOBS_DB.STAGE.JOBS_WITH_SALARY
AS
SELECT
	JU.*,
	JLE.SALARY_MIN,
	JLE.SALARY_MAX
FROM BETTERJOBS_DB.STAGE.JOBS_UNIFIED JU
INNER JOIN BETTERJOBS_DB.STAGE.JOBS_LLM_ENRICHED JLE ON JU.JOB_UID = JLE.JOB_UID
WHERE JLE.SALARY_MIN IS NOT NULL OR JLE.SALARY_MAX IS NOT NULL;








