create or replace view BETTERJOBS_DB.STAGE.SKILL_CATEGORY_PATTERNS_ANALYSIS(
	SKILL_CATEGORY,
	TOTAL_PATTERNS,
	ACTIVE_PATTERNS,
	INACTIVE_PATTERNS,
	AVG_CONFIDENCE,
	MIN_CONFIDENCE,
	MAX_CONFIDENCE,
	ACTIVE_PATTERN_LIST
) as
SELECT
    SKILL_CATEGORY,
    COUNT(*) as TOTAL_PATTERNS,
    COUNT(CASE WHEN IS_ACTIVE = TRUE THEN 1 END) as ACTIVE_PATTERNS,
    COUNT(CASE WHEN IS_ACTIVE = FALSE THEN 1 END) as INACTIVE_PATTERNS,
    AVG(CONFIDENCE_SCORE) as AVG_CONFIDENCE,
    MIN(CONFIDENCE_SCORE) as MIN_CONFIDENCE,
    MAX(CONFIDENCE_SCORE) as MAX_CONFIDENCE,
    ARRAY_AGG(CASE WHEN IS_ACTIVE = TRUE THEN PATTERN END) as ACTIVE_PATTERN_LIST
FROM SKILL_CATEGORY_PATTERNS
GROUP BY SKILL_CATEGORY
ORDER BY TOTAL_PATTERNS DESC;