CREATE VIEW IF NOT EXISTS BETTERJOBS_DB.STAGE.SALARY_RAW_EXTRACTION AS
SELECT
    jle.JOB_UID,

    -- Original salary values
    jle.SALARY_MIN,
    jle.SALARY_MAX,
    COALESCE(LOWER(TRIM(jle.SALARY_PERIOD)), 'unknown') as SALARY_PERIOD,
    COALESCE(UPPER(TRIM(jle.SALARY_CURRENCY)), 'USD') as SALARY_CURRENCY,

    -- Data quality indicators
    CASE
        WHEN jle.SALARY_MIN IS NOT NULL AND jle.SALARY_MAX IS NOT NULL THEN 'complete_range'
        WHEN jle.SALARY_MIN IS NOT NULL AND jle.SALARY_MAX IS NULL THEN 'min_only'
        WHEN jle.SALARY_MIN IS NULL AND jle.SALARY_MAX IS NOT NULL THEN 'max_only'
        ELSE 'no_salary'
    END as SALARY_COMPLETENESS,

    -- Outlier detection flags (will be refined in normalization)
    CASE
        WHEN jle.SALARY_MIN > 1000000 OR jle.SALARY_MAX > 1000000 THEN TRUE
        WHEN jle.SALARY_MIN < 1 OR jle.SALARY_MAX < 1 THEN TRUE
        ELSE FALSE
    END as POTENTIAL_OUTLIER_FLAG,

    -- Job metadata for context
    ju.PLATFORM,
    ju.DATE_RETRIEVED,
    cp.COMPANY_NAME_STANDARDIZED as COMPANY_NAME

FROM BETTERJOBS_DB.STAGE.JOBS_LLM_ENRICHED jle
JOIN BETTERJOBS_DB.STAGE.JOBS_UNIFIED ju ON jle.JOB_UID = ju.JOB_UID
LEFT JOIN BETTERJOBS_DB.STAGE.COMPANY_PROFILES cp ON ju.COMPANY_ID = cp.COMPANY_ID
WHERE (jle.SALARY_MIN IS NOT NULL OR jle.SALARY_MAX IS NOT NULL)
  AND (jle.SALARY_MIN > 0 OR jle.SALARY_MAX > 0)
  AND COALESCE(jle.SALARY_MIN, 0) != COALESCE(jle.SALARY_MAX, 0)  -- Remove same min/max as likely errors