Skip to main content
Skip to editor
Skip to results
Site
Worksheets
Selection deleted
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
SELECT TOP 1 * FROM BETTERJOBS_DB.STAGE.LLM_MANUAL_REVIEW_QUEUE


SELECT
    CURRENT_TIMESTAMP as report_timestamp,
    -- Coverage
    (SELECT ROUND(AVG(CASE WHEN jsb.JOB_UID IS NOT NULL THEN 1 ELSE 0 END) * 100, 2)
     FROM BETTERJOBS_DB.STAGE.JOBS_UNIFIED ju
     LEFT JOIN BETTERJOBS_DB.STAGE.JOB_SKILLS_BRIDGE jsb ON ju.JOB_UID = jsb.JOB_UID) as skills_coverage_pct,

    -- Quality
    (SELECT ROUND(AVG(OVERALL_CONFIDENCE), 3)
     FROM BETTERJOBS_DB.STAGE.JOB_SKILLS_BRIDGE) as avg_skills_confidence,

    -- Volume
    (SELECT COUNT(*) FROM BETTERJOBS_DB.STAGE.SKILLS_NORMALIZED) as total_skills,
    (SELECT COUNT(*) FROM BETTERJOBS_DB.STAGE.KEYWORDS_NORMALIZED) as total_keywords,
    (SELECT COUNT(*) FROM BETTERJOBS_DB.STAGE.LOCATIONS_NORMALIZED) as total_locations,

    -- Issues
    (SELECT COUNT(*) FROM BETTERJOBS_DB.STAGE.LLM_MANUAL_REVIEW_QUEUE WHERE REVIEW_STATUS = 'PENDING') as pending_reviews,
    (SELECT COUNT(*) FROM BETTERJOBS_DB.STAGE.LLM_QUALITY_VALIDATION_RESULTS
     WHERE ISSUE_TYPE IS NOT NULL AND STATUS = 'ACTIVE') as current_issues;
Query Details
Query duration
79ms
Rows
1
Query ID
01bd0f3f-0000-215b-0014-e60b00088ade
REVIEW_ID
100% filled
ITEM_TYPE
100% filled
ITEM_ID
100% filled
DATA_SOURCE
100% filled
REVIEW_REASON
100% filled
PRIORITY_SCORE
100% filled
CONFIDENCE_SCORE
100% filled
ORIGINAL_VALUE
100% filled
SUGGESTED_VALUE
100% filled
BUSINESS_IMPACT
100% filled
REVIEW_STATUS
100% filled
ASSIGNED_TO
0% filled
100% null
ASSIGNED_AT
0% filled
100% null
REVIEWED_AT
0% filled
100% null
REVIEWER_DECISION
0% filled
100% null
REVIEWER_COMMENTS
0% filled
100% null
APPROVED_VALUE
0% filled
100% null
CREATED_TIMESTAMP
100% filled
UPDATED_TIMESTAMP
100% filled
CREATED_BY
100% filled
Databases
Worksheets
Search objects
JOBS_WITH_SALARY
JOB_ID
VARCHAR(16777216)
COMPANY_ID
VARCHAR(16777216)
PLATFORM
VARCHAR(16777216)
JOB_TITLE_CLEAN
VARCHAR(16777216)
JOB_DESCRIPTION_CLEAN
VARCHAR(16777216)
COMPANY_NAME_CLEAN
VARCHAR(16777216)
LOCATION_STANDARDIZED
VARCHAR(16777216)
JOB_URL
VARCHAR(16777216)
DATE_POSTED
DATE
DATE_RETRIEVED
TIMESTAMP_NTZ(9)
IS_ACTIVE
BOOLEAN
EMPLOYMENT_STATUS
VARCHAR(16777216)
DEPARTMENT
VARCHAR(16777216)
DETECTED_LANGUAGE
VARCHAR(16777216)
LANGUAGE_CONFIDENCE
FLOAT
IS_ENGLISH
BOOLEAN
LANGUAGE_DETECTION_METHOD
VARCHAR(16777216)
SALARY_MIN
NUMBER(38,0)
SALARY_MAX
NUMBER(38,0)
SALARY_CURRENCY
VARCHAR(16777216)
SALARY_PERIOD
VARCHAR(16777216)
SALARY_CONFIDENCE
FLOAT
MIN_YEARS_EXPERIENCE
NUMBER(38,0)
MAX_YEARS_EXPERIENCE
NUMBER(38,0)
EXPERIENCE_LEVEL
VARCHAR(16777216)
EDUCATION_REQUIREMENTS
VARIANT
PROGRAMMING_LANGUAGES
VARIANT
DATABASES
VARIANT
CLOUD_PLATFORMS
VARIANT
FRAMEWORKS
VARIANT
TOOLS
VARIANT
SOFT_SKILLS
VARIANT
WORK_TYPE
VARCHAR(16777216)
REMOTE_FLEXIBILITY
VARCHAR(16777216)
TRAVEL_REQUIREMENTS
VARCHAR(16777216)
OFFICE_LOCATIONS
VARIANT
PRIMARY_KEYWORDS
VARIANT
INDUSTRY_KEYWORDS
VARIANT
ROLE_TYPE_KEYWORDS
VARIANT
COMPANY_STAGE_KEYWORDS
VARIANT
JOB_FAMILY
VARCHAR(16777216)
JOB_SUB_FAMILY
VARCHAR(16777216)
PLATFORM_SPECIFIC_DATA
VARIANT
TRANSFORMATION_TIMESTAMP
TIMESTAMP_NTZ(9)
DATA_QUALITY_SCORE
FLOAT
EXTRACTION_CONFIDENCE_AVG
FLOAT
KEYWORD_QUALITY_SCORE
FLOAT
SOURCE_RAW_TABLE
VARCHAR(16777216)
RAW_DATA
VARIANT
PARTITION_DATE
DATE
Ask Copilot

View Definition
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
create if not exists view BETTERJOBS_DB.STAGE.JOBS_WITH_SALARY(
	JOB_ID,
	COMPANY_ID,
	PLATFORM,
	JOB_TITLE_CLEAN,
	JOB_DESCRIPTION_CLEAN,
	COMPANY_NAME_CLEAN,
	LOCATION_STANDARDIZED,
	JOB_URL,
	DATE_POSTED,
	DATE_RETRIEVED,
	IS_ACTIVE,
	EMPLOYMENT_STATUS,
	DEPARTMENT,
	DETECTED_LANGUAGE,
	LANGUAGE_CONFIDENCE,
	IS_ENGLISH,
	LANGUAGE_DETECTION_METHOD,
	SALARY_MIN,
	SALARY_MAX,
	SALARY_CURRENCY,
	SALARY_PERIOD,
	SALARY_CONFIDENCE,
	MIN_YEARS_EXPERIENCE,
	MAX_YEARS_EXPERIENCE,
	EXPERIENCE_LEVEL,
	EDUCATION_REQUIREMENTS,
	PROGRAMMING_LANGUAGES,
	DATABASES,
	CLOUD_PLATFORMS,
	FRAMEWORKS,
	TOOLS,
	SOFT_SKILLS,
	WORK_TYPE,
	REMOTE_FLEXIBILITY,
	TRAVEL_REQUIREMENTS,
	OFFICE_LOCATIONS,
	PRIMARY_KEYWORDS,
	INDUSTRY_KEYWORDS,
	ROLE_TYPE_KEYWORDS,
	COMPANY_STAGE_KEYWORDS,
	JOB_FAMILY,
	JOB_SUB_FAMILY,
	PLATFORM_SPECIFIC_DATA,
	TRANSFORMATION_TIMESTAMP,
	DATA_QUALITY_SCORE,
	EXTRACTION_CONFIDENCE_AVG,
	KEYWORD_QUALITY_SCORE,
	SOURCE_RAW_TABLE,
	RAW_DATA,
	PARTITION_DATE
) as
SELECT * FROM jobs_unified
WHERE salary_min IS NOT NULL OR salary_max IS NOT NULL;
Sorted by Viewed descending
