CREATE VIEW IF NOT EXISTS BETTERJOBS_DB.STAGE.Z_REVIEW_SALARY_QUEUE(
    JOB_UID,
    JOB_DESCRIPTION_CLEAN,
    JOB_URL,
    SALARY_MIN,
    SALARY_MAX,
    SALARY_PERIOD,
    SALARY_CURRENCY,
    SALARY_CONFIDENCE,
    SALARY_RANGE_NAME,
    SALARY_MIN_ORIGINAL,
    SALARY_MAX_ORIGINAL,
    SALARY_PERIOD_ORIGINAL,
    SALARY_MIN_ANNUAL_USD,
    SALARY_MAX_ANNUAL_USD
) AS
SELECT
    JU.JOB_UID,
    JU.JOB_DESCRIPTION_CLEAN,
    JU.JOB_URL,
    JLE.SALARY_MIN,
    JLE.SALARY_MAX,
    JLE.SALARY_PERIOD,
    JLE.SALARY_CURRENCY,
    JLE.SALARY_CONFIDENCE,
    SN.SALARY_RANGE_NAME,
    SN.SALARY_MIN_ORIGINAL,
    SN.SALARY_MAX_ORIGINAL,
    SN.SALARY_PERIOD_ORIGINAL,
    SN.SALARY_MIN_ANNUAL_USD,
    SN.SALARY_MAX_ANNUAL_USD
FROM BETTERJOBS_DB.STAGE.JOB_SALARY_BRIDGE JSB
INNER JOIN BETTERJOBS_DB.STAGE.JOBS_LLM_ENRICHED JLE
    ON JLE.JOB_UID = JSB.JOB_UID
INNER JOIN BETTERJOBS_DB.STAGE.SALARY_NORMALIZED SN
    ON SN.SALARY_ID = JSB.SALARY_ID
INNER JOIN BETTERJOBS_DB.STAGE.JOBS_UNIFIED JU
    ON JU.JOB_UID = JLE.JOB_UID
WHERE JSB.NEEDS_REVIEW = TRUE;