CREATE OR REPLACE VIEW BETTERJOBS_DB.STAGE.EXPERIENCE_RAW_EXTRACTION AS
WITH MIN_YEARS_EXTRACTED AS (
    -- Extract MIN_YEARS_EXPERIENCE records
    SELECT
        CONCAT('exp_', JOB_UID, '_min_years') as EXTRACTION_ID,
        JOB_UID,
        'min_years' as EXPERIENCE_SOURCE,
        'general' as EXPERIENCE_TYPE,
        MIN_YEARS_EXPERIENCE as EXPERIENCE_VALUE,
        CAST(MIN_YEARS_EXPERIENCE AS STRING) as ORIGINAL_TEXT,
        EXPERIENCE_CONFIDENCE as EXTRACTION_CONFIDENCE,
        NULL as TECHNOLOGY_NAME
    FROM BETTERJOBS_DB.STAGE.JOBS_LLM_ENRICHED
    WHERE MIN_YEARS_EXPERIENCE IS NOT NULL
      AND MIN_YEARS_EXPERIENCE > 0
),

MAX_YEARS_EXTRACTED AS (
    -- Extract MAX_YEARS_EXPERIENCE records
    SELECT
        CONCAT('exp_', JOB_UID, '_max_years') as EXTRACTION_ID,
        JOB_UID,
        'max_years' as EXPERIENCE_SOURCE,
        'general' as EXPERIENCE_TYPE,
        MAX_YEARS_EXPERIENCE as EXPERIENCE_VALUE,
        CAST(MAX_YEARS_EXPERIENCE AS STRING) as ORIGINAL_TEXT,
        EXPERIENCE_CONFIDENCE as EXTRACTION_CONFIDENCE,
        NULL as TECHNOLOGY_NAME
    FROM BETTERJOBS_DB.STAGE.JOBS_LLM_ENRICHED
    WHERE MAX_YEARS_EXPERIENCE IS NOT NULL
      AND MAX_YEARS_EXPERIENCE > 0
),

EXPERIENCE_LEVEL_EXTRACTED AS (
    -- Extract EXPERIENCE_LEVEL records
    SELECT
        CONCAT('exp_', JOB_UID, '_level') as EXTRACTION_ID,
        JOB_UID,
        'experience_level' as EXPERIENCE_SOURCE,
        'role_level' as EXPERIENCE_TYPE,
        PARSE_JSON(CONCAT('"', EXPERIENCE_LEVEL, '"')) as EXPERIENCE_VALUE,
        EXPERIENCE_LEVEL as ORIGINAL_TEXT,
        EXPERIENCE_CONFIDENCE as EXTRACTION_CONFIDENCE,
        NULL as TECHNOLOGY_NAME
    FROM BETTERJOBS_DB.STAGE.JOBS_LLM_ENRICHED
    WHERE EXPERIENCE_LEVEL IS NOT NULL
      AND TRIM(EXPERIENCE_LEVEL) != ''
      AND LOWER(TRIM(EXPERIENCE_LEVEL)) NOT IN ('null', 'none', 'n/a', 'unknown')
),

SENIORITY_LEVEL_EXTRACTED AS (
    -- Extract SENIORITY_LEVEL records
    SELECT
        CONCAT('exp_', JOB_UID, '_seniority') as EXTRACTION_ID,
        JOB_UID,
        'seniority_level' as EXPERIENCE_SOURCE,
        'role_level' as EXPERIENCE_TYPE,
        PARSE_JSON(CONCAT('"', SENIORITY_LEVEL, '"')) as EXPERIENCE_VALUE,
        SENIORITY_LEVEL as ORIGINAL_TEXT,
        EXPERIENCE_CONFIDENCE as EXTRACTION_CONFIDENCE,
        NULL as TECHNOLOGY_NAME
    FROM BETTERJOBS_DB.STAGE.JOBS_LLM_ENRICHED
    WHERE SENIORITY_LEVEL IS NOT NULL
      AND TRIM(SENIORITY_LEVEL) != ''
      AND LOWER(TRIM(SENIORITY_LEVEL)) NOT IN ('null', 'none', 'n/a', 'unknown')
),

TECHNOLOGY_SPECIFIC_EXTRACTED AS (
    -- Extract SPECIFIC_TECHNOLOGIES_YEARS records (flatten JSON)
    SELECT
        CONCAT('exp_', JOB_UID, '_tech_', TECH.KEY) as EXTRACTION_ID,
        JOB_UID,
        'specific_tech' as EXPERIENCE_SOURCE,
        'technology_specific' as EXPERIENCE_TYPE,
        TECH.VALUE as EXPERIENCE_VALUE,
        CONCAT(TECH.KEY, ': ', TECH.VALUE, ' years') as ORIGINAL_TEXT,
        EXPERIENCE_CONFIDENCE as EXTRACTION_CONFIDENCE,
        TECH.KEY as TECHNOLOGY_NAME
    FROM BETTERJOBS_DB.STAGE.JOBS_LLM_ENRICHED,
    LATERAL FLATTEN(input => SPECIFIC_TECHNOLOGIES_YEARS) TECH
    WHERE SPECIFIC_TECHNOLOGIES_YEARS IS NOT NULL
      AND TECH.VALUE IS NOT NULL
      AND TRY_TO_NUMBER(TECH.VALUE::STRING) > 0
)

SELECT * FROM MIN_YEARS_EXTRACTED
UNION ALL
SELECT * FROM MAX_YEARS_EXTRACTED
UNION ALL
SELECT * FROM EXPERIENCE_LEVEL_EXTRACTED
UNION ALL
SELECT * FROM SENIORITY_LEVEL_EXTRACTED
UNION ALL
SELECT * FROM TECHNOLOGY_SPECIFIC_EXTRACTED;