create if not exists view BETTERJOBS_DB.STAGE.SKILLS_QUALITY_REPORT(
	SKILL_CATEGORY,
	TOTAL_SKILLS,
	HIGH_CONFIDENCE_SKILLS,
	LOW_CONFIDENCE_SKILLS,
	NEEDS_REVIEW,
	AVG_CONFIDENCE,
	AVG_FREQUENCY
) as
SELECT
    SKILL_CATEGORY,
    COUNT(*) as TOTAL_SKILLS,
    COUNT(CASE WHEN CONFIDENCE_SCORE >= 0.8 THEN 1 END) as HIGH_CONFIDENCE_SKILLS,
    COUNT(CASE WHEN CONFIDENCE_SCORE < 0.5 THEN 1 END) as LOW_CONFIDENCE_SKILLS,
    COUNT(CASE WHEN MANUAL_REVIEW_FLAG THEN 1 END) as NEEDS_REVIEW,
    AVG(CONFIDENCE_SCORE) as AVG_CONFIDENCE,
    AVG(FREQUENCY_COUNT) as AVG_FREQUENCY
FROM SKILLS_NORMALIZED
GROUP BY SKILL_CATEGORY
ORDER BY TOTAL_SKILLS DESC;