create or replace view BETTERJOBS_DB.STAGE.COUNTRIES_LOOKUP(
	COUNTRY_NAME,
	COUNTRY_CODE_ISO2,
	REGION,
	IS_MAJOR_TECH_HUB
) as
SELECT COUNTRY_NAME_COMMON as COUNTRY_NAME, COUNTRY_CODE_ISO2, REGION, IS_MAJOR_TECH_HUB FROM COUNTRIES_MAPPING
UNION ALL
SELECT COUNTRY_NAME_OFFICIAL as COUNTRY_NAME, COUNTRY_CODE_ISO2, REGION, IS_MAJOR_TECH_HUB FROM COUNTRIES_MAPPING
WHERE COUNTRY_NAME_OFFICIAL != COUNTRY_NAME_COMMON;