create if not exists view BETTERJOBS_DB.STAGE.LOCATIONS_ANALYSIS(
	LOCATION_NAME,
	CITY,
	STATE_PROVINCE,
	COUNTRY,
	LOCATION_TYPE,
	FREQUENCY,
	PLATFORMS,
	AVG_CONFIDENCE,
	IS_REMOTE_FRIENDLY,
	IS_MAJOR_TECH_HUB,
	TOTAL_MARKET_FREQUENCY
) as
SELECT
    ln.LOCATION_NAME,
    ln.CITY,
    ln.STATE_PROVINCE,
    ln.COUNTRY,
    ln.LOCATION_TYPE,
    COUNT(DISTINCT jlb.JOB_UID) as FREQUENCY,
    ARRAY_AGG(DISTINCT j.PLATFORM) as PLATFORMS,
    AVG(jlb.OVERALL_CONFIDENCE) as AVG_CONFIDENCE,
    ln.IS_REMOTE_FRIENDLY,
    ln.IS_MAJOR_TECH_HUB,
    ln.FREQUENCY_COUNT as TOTAL_MARKET_FREQUENCY
FROM LOCATIONS_NORMALIZED ln
LEFT JOIN JOB_LOCATIONS_BRIDGE jlb ON ln.LOCATION_ID = jlb.LOCATION_ID
LEFT JOIN JOBS_UNIFIED j ON jlb.JOB_UID = j.JOB_UID
WHERE j.IS_ENGLISH = TRUE OR j.IS_ENGLISH IS NULL
GROUP BY ln.LOCATION_NAME, ln.CITY, ln.STATE_PROVINCE, ln.COUNTRY, ln.LOCATION_TYPE,
         ln.IS_REMOTE_FRIENDLY, ln.IS_MAJOR_TECH_HUB, ln.FREQUENCY_COUNT
ORDER BY FREQUENCY DESC;