CREATE VIEW IF NOT EXISTS BETTERJOBS_DB.STAGE.JOB_LOCATIONS_COVERAGE(
	TOTAL_JOBS,
	JOBS_WITH_LOCATIONS,
	COVERAGE_PERCENTAGE,
	AVG_LOCATIONS_PER_JOB
) as
SELECT
    COUNT(DISTINCT ju.JOB_UID) as TOTAL_JOBS,
    COUNT(DISTINCT jlb.JOB_UID) as JOBS_WITH_LOCATIONS,
    ROUND((COUNT(DISTINCT jlb.JOB_UID)::FLOAT / COUNT(DISTINCT ju.JOB_UID)) * 100, 2) as COVERAGE_PERCENTAGE,
    AVG(locations_per_job.LOCATION_COUNT) as AVG_LOCATIONS_PER_JOB
FROM JOBS_UNIFIED ju
LEFT JOIN JOB_LOCATIONS_BRIDGE jlb ON ju.JOB_UID = jlb.JOB_UID
LEFT JOIN (
    SELECT JOB_UID, COUNT(*) as LOCATION_COUNT
    FROM JOB_LOCATIONS_BRIDGE
    GROUP BY JOB_UID
) locations_per_job ON ju.JOB_UID = locations_per_job.JOB_UID;