create if not exists view BETTERJOBS_DB.STAGE.TOP_SKILLS_BY_CATEGORY(
	SKILL_CATEGORY,
	SKILL_NAME,
	FREQUENCY_COUNT,
	TREND_DIRECTION,
	CONFIDENCE_SCORE,
	RANK_IN_CATEGORY
) as
SELECT
    SKILL_CATEGORY,
    SKILL_NAME,
    FREQUENCY_COUNT,
    TREND_DIRECTION,
    CONFIDENCE_SCORE,
    ROW_NUMBER() OVER (PARTITION BY SKILL_CATEGORY ORDER BY FREQUENCY_COUNT DESC) as RANK_IN_CATEGORY
FROM SKILLS_NORMALIZED
WHERE CONFIDENCE_SCORE >= 0.8
ORDER BY SKILL_CATEGORY, RANK_IN_CATEGORY;